CollaBu/pennyway-was

pennyway-domain/build.gradle, pennyway-domain/src/main/java/kr/co/pennyway/common/annotation/DomainRedisCacheManager.java, pennyway-domain/src/main/java/kr/co/pennyway/common/annotation/DomainRedisConnectionFactory.java, pennyway-domain/src/main/java/kr/co/pennyway/common/annotation/DomainRedisTemplate.java, pennyway-domain/src/main/java/kr/co/pennyway/config/RedisConfig.java, pennyway-domain/src/main/resources/application-domain.yml, pennyway-infra/build.gradle, pennyway-infra/src/main/java/kr/co/infra/common/annotation/InfraRedisConnectionFactory.java, pennyway-infra/src/main/java/kr/co/infra/common/annotation/OidcCacheManager.java, pennyway-infra/src/main/java/kr/co/infra/common/annotation/SecurityUserCacheManager.java, pennyway-infra/src/main/java/kr/co/infra/config/CacheConfig.java
- domain 모듈에 Redis Repository를 위한 Config 설정
- infra 모듈에 Caching을 위한 Config 설정
<br/>
```java
@Configuration
@EnableRedisRepositories
@EnableTransactionManagement
public class RedisConfig {
```
- `RefreshToken`과 같이 단순 캐싱이 아닌 `Domain Service` 수준의 비지니스 로직이 필요한 데이터를 관리하기 위함.
- `implementation`으로 redis 의존성을 주입한다.
<br/>
```java
@Configuration
@EnableCaching
public class CacheConfig {
...
}
```
- `@Cacheable`, `@CacheEvict` 어노테이션 등을 활용하는 경우 사용
- 일반적인 cache는 `defaultCacheManager()`를 통해 캐싱을 관리하며, `ttl = 60sec`이다.
- 별도의 세팅값을 가져야 하는 `securityUserCacheManager`와 `oidcCacheManager`는 `Custom Qualify`로 `Bean`을 추가 등록
- `api`로 redis 의존성을 주입한다.
<br/>
**🟡 예시**
```java
@Slf4j
@Service
@RequiredArgsConstructor
public class UserDetailServiceImpl implements UserDetailsService {
private final MemberRepository …
```
=> ✨ Redis Configuration 설정

pennyway-app-external-api/build.gradle, pennyway-app-external-api/src/main/java/kr/co/pennyway/config/SwaggerConfig.java, pennyway-app-external-api/src/main/resources/application.yml, pennyway-common/src/main/resources/application-common.yml, pennyway-domain/src/main/resources/application-domain.yml, pennyway-infra/src/main/resources/application-infra.yml
- OpenApi 의존성 주입을 통한 Swagger UI 구성
<br/>
```gradle
implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0'
```
- `infra` 모듈에 세팅하려 했으나, 하위 모든 application 모듈이 swagger를 사용하진 않을 거 같아 `extenal-api` 모듈에 주입했습니다.
- 추후 필요성이 느껴지면 infra 모듈로 옮겨도 되니, "결정되지 않은 사항들을 최대한 미루라"는 원칙을 준수하기로 했습니다.
<br/>
```yml
springdoc:
default-consumes-media-type: application/json;charset=UTF-8
default-produces-media-type: application/json;charset=UTF-8
swagger-ui:
path: /swagger-ui
disable-swagger-default-url: true
display-request-duration: true
operations-sorter: alpha
api-docs:
groups:
enabled: true
```
- local, dev 모두 `/swagger-ui`를 end-point로 설정해두었습니다.
- dev의 swagger 경로를 감춰야 한다고 하면 환경 변수로 주입하도록 변경하겠습니다.
<br/>
</div>
- 개발 서버 환경에선 `사진(2)`의 `Developer Server`를 선택하시면 됩니다.
- …
=> ✨ OpenAPI Swagger config 설정

pennyway-app-external-api/src/main/resources/application.yml
- Swagger 관련 환경 변수 오타 수정
<br/>
- `external-api`의 환경 변수 파일인 `application.yml`의 'pennywah' => 'pennyway'로 수정
<br/>
- 없음
<br/>
- 없음
=> Swagger 관련 환경 변수 오타 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/Jwts.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneCertificationReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/JwtAuthMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/Jwts.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/refresh/RefreshTokenProvider.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/util/CookieUtil.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/NotEmoji.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/NotEmojiValidator.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/NotWhiteSpace.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/NotWhiteSpaceValidator.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/Password.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/validator/PasswordValidator.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/AuthControllerValidationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/response/SuccessResponseTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/security/jwt/access/AccessTokenProviderTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshToken.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenServiceImpl.java
> 805줄이지만 테스트 코드만 216줄이고, 대부분 유효성 검사 때문에 뻥튀기 된 겁니다.
- 회원 가입 시, 요청 DTO 유효성 Application 레벨 validation check
- RTR 기법 적용 및 redis 저장을 위한 refresh token 관련 클래스 정의 (도메인, 도메인 서비스, 레포지토리 정의)
- 3가지 커스텀 Validator 어노테이션 작성
- 쿠키 유틸 작성
<br/>
- RedisHash를 사용하여 RefreshToken Entity 정의
- RefreshTokenService 3가지 공개 메서드 제공 (저장, 리프레시, 삭제) 
- `@NotWhiteSpace`: 어노테이션된 요소는 반드시 공백문자가 포함되어서는 안 됩니다. (단, null인 경우 true를 반환합니다.)
- `@NotEmoji`: 어노테이션된 요소는 반드시 이모지가 포함되어서는 안 됩니다. (단, null인 경우 true를 반환합니다.)
- `@Password`: 어노테이션된 요소는 반드시 8~16자의 영문 대/소문자, 숫자, 특수문자를 사용해야 합니다. 적어도 하나 이상의 소문자 알파벳과 숫자가 포함되어야 합니다.
- cookie 확인, 수정, 삭제를 위한 유틸입니다.
- 인증 파트 말고 사용할 일 거의 없겠지만, 궁금하신 부분은 질문 주시면 답변해드리겠습니다.
- username: 5~20자, 영문 소문자, 특수기호 `-`, `_`, `.` (그외 특수기호, 공백 사용 불가)
- name: 한글, 영문 대/소문자 (특수기호, 공백 사용 불가)
- password: 8~16자의 영문 대/소문, …
=> ✨️ 회원가입 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/annotation/RefreshTokenStrategy.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtAuthenticationFilter.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtExceptionFilter.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/handler/JwtAccessDeniedHandler.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/handler/JwtAuthenticationEntryPoint.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/JwtSecurityConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityFilterConfig.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/forbidden/ForbiddenToken.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/forbidden/ForbiddenTokenRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/forbidden/ForbiddenTokenService.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/exception/JwtErrorCode.java
- Refresh token refresh api 개방
- Jwt 인증 필터 작성
- WebSecurity 인증/인가 예외 핸들러 작성
- MethodSecurity 인증/인가 예외 핸들링
리프레시 기능은 안 했어야 했는데, 자꾸 토큰 만료되는 덕에 테스트가 너무 힘들어서 그만..
<br/>
**📨 요청**
- url : `/v1/auth/refresh`
- header
- `Set-Cookie`: refresh token 정보
- pre-condition: 인증되지 않은 유저만 허용
<br/>
**📢 응답**
- header
- `Set-Cookie`: refresh token 정보
- `Authorization`: access token 정보
- body
```json
{
"data": {
"user": {
"id": 1 // 로그인한 사용자 pk
}
}
}
```
<br/>
**🟡 탈취 시나리오 (RTR)**
- 재현 방법
1. 로그인을 하고 refresh token 정보 저장
2. refresh api 호출
3. 새로 발급받은 refresh 토큰을 (1)의 토큰으로 변경
4. refresh api 재호출
</div>
<br/>
</div>
- 순서는 `JwtExceptionFilter` → `JwtAuthenticationFilter`로 진행됩니다.
- `Authentication` 헤더가 없는 유저는 SecurityUser 객체를 생성하지 않고 `anonymous` 권한으로 진행합니다.
- …
=> ✨ Jwt 인증 필터

.github/workflows/deploy.yml, pennyway-app-external-api/build.gradle, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignInReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/CustomGrantedAuthority.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/JacksonConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/SwaggerConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/CorsConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityAdapterConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityAuthConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java, pennyway-app-external-api/src/main/resources/application.yml, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/ServerProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/config/ConfigurationPropertiesConfig.java, pennyway-infra/src/main/resources/application-infra.yml
> `/swapfile` 크기 조정하느라, 서버에서 내려주는 Swagger 문서는 아직 테스트는 못 해봤습니다.
- Security Filter 에서 캐싱된 인증 유저가 역직렬화에 실패함.
- Swagger 문서에 일부 DTO가 누락되거나, 잘못된 DTO가 표시됨.
- Swagger 문서에서 요청을 보내면 잘못된 request url이 설정됨.
<br/>
```java
@Getter
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class SecurityUserDetails implements UserDetails {
@Serial
private static final long serialVersionUID = 1L;
private Long userId;
private String username;
private Collection<? extends GrantedAuthority> authorities;
private boolean accountNonLocked;
@JsonIgnore
private boolean enabled;
@JsonIgnore
private String password;
@JsonIgnore
private boolean credentialsNonExpired;
@JsonIgnore
private boolean accountNonExpired;
...
}
```
- `GrantedAuthority`를 구현하는 `SimpleGrantedAuthority`를 사용했으나 직렬화/역직렬화 지원 안 함
- 공식 문서를 참고하여 …
=> ✏️ Swagger + Security 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthCheckUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/repository/UserRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java
- 닉네임 중복 검사용 API 개방
<br/>
**📨 요청**
- url : `GET /v1/duplication/username`
- parameter: username=검사하려는 닉네임
- pre-condition: permitAll
- 요청 예시: `/v1/duplication/username?username=jayang`
<br/>
**📢 응답**
- body
```json
{
"data": {
"isDuplicate": false // or true
}
}
```
<br/>
- 닉네임 중복 검사는 범용적으로 쓰일 수 있어서 API를 별도로 분리했습니다.
- 기존의 Security Config에 설정한 Swagger 요청 경로는 분리하고, read only public endpoints를 따로 설정했습니다.
<br/>
- 없음
=> ✨ 닉네임 중복검사 API

pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java
- idToken의 `kid` 값을 추출하기 위해 signature 검증 없이 decoding
<br/>
- provider가 제공하는 keys는 다음과 같은 정보를 포함합니다.
- kid, kty, alg, se, n, e (해당 정보를 여러 개 제공함)
- JWS를 복호화하기 위해서는 `n`, `e` 값을 통해 `public key`를 유추해야 합니다.
```java
/**
* n, e 조합으로 공개키를 생성하는 메서드
*/
private PublicKey getRSAPublicKey(String modulus, String exponent) throws NoSuchAlgorithmException, InvalidKeySpecException {
KeyFactory keyFactory = KeyFactory.getInstance(RSA);
byte[] decodeN = Base64.getUrlDecoder().decode(modulus);
byte[] decodeE = Base64.getUrlDecoder().decode(exponent);
BigInteger n = new BigInteger(1, decodeN);
BigInteger e = new BigInteger(1, decodeE);
RSAPublicKeySpec publicKeySpec = new RSAPublicKeySpec(n, e);
return keyFactory.generatePublic(publicKeySpec);
}
```
- 하지만 provider에서 제공하는 keys는 배열이므로, 어떤 `n`, `e`를 택할 지 판단 기준이 …
=> 🐛 OIDC signature 검증없이 header, payload 추출 로직 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/ErrorResponse.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/swagger/CustomJsonView.java
- Oauth 전화번호 검증 응답 문서 오류 수정
- Auth Controller 문서 주석 분리
- Error 응답 문서 개선
<br/>
</div>
- `existsUser`를 `existUser`로 오기입한 부분 수정
<br/>
- `AuthApi` 인터페이스로 문서 주석 분리
- 이전보다 상세하게 응답 포맷 명시
<br/>
**🔴 As-is**
</div>
- Error와 Fail을 모두 ErrorResponse로 관리하다보니, 422에러만 나타나는 `fieldErrors`가 모든 응답에서 표기됨
- `hidden = true` 옵션을 주면 모든 응답에서 보이지 않게 되므로, 이 방법 또한 적절하지 않음.
<br/>
**🟢 To-be**
</div>
```java
public class CustomJsonView {
public static class Common {
}
public static class Hidden extends Common {
}
}
```
- `@JsonView`를 사용하면 동일한 POJO 오브젝트에서 선택적으로 서로 다른 property가 조합된 JSON 문자열을 생성할 수 있음.
- `CustomJsonView` 클래스와 `@JsonView` 어노테이션을 활용하여 선택적으로 보여질 필드를 조정함.
<br/>
- AuthApi 문서 응답에 오탈자 혹은 잘못된 응답이 있는지?
<br/>
- ControllerAdvice에 의해 특정 API에서 발생하지 않는 예외까지 …
=> 📝 Swagger 예외 응답 문서 개선

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/OauthOidcHelper.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcClientProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/AppleOidcProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/GoogleOidcProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/KakaoOidcProperties.java, pennyway-infra/src/main/resources/application-infra.yml
- google id token payload의 `iss` 불일치 문제 
<br/>
- apple, kakao와 달리 google은 `jwks_uri`와 `issuer`가 다름.
- google의 issure을 추가로 등록
- 로컬에서 모두 정상적으로 검증되는 것 확인했습니다!
<br/>
- 환경 변수로 `GOOGLE_ISSUER`가 추가되었고, 노션 업데이트 해두었습니다. 
<br/>
- 파싱 실패시 `500 Error` 발생하는 것 수정
- 기존에는 `jjwt` 유틸을 사용해서 헤더의 `kid`를 가져왔는데, 자체적으로 decode 했더니 `aud`, `iss` 비교 실패 시 서버 에러 응답으로 반환되고 있었음.
=> 🐛 Google id token issuer mismatch 이슈 해결

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java
- User Entity의 name 도메인 변경에 의한 유효성 검사 변경
<br/>
- name 필드 정규 표현식 수정 (2~8자의 한글, 영문 소문자만 사용 가능합니다.)
- 하는 김에 거슬렸던 로그 레벨 수정 하나랑, 지난 번에 빠트리고 push 안 했던 예외 처리도 살짝쿵...ㅎㅎ
<br/>
- 정규 표현식 오류 있는지?
<br/>
- 없음
=> ✏️ User name 필드 유효성 검사 기준 변경

pennyway-domain/build.gradle, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/config/ContainerMySqlTestConfig.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserSoftDeleteTest.java, pennyway-domain/src/test/resources/logback-test.xml
- User, Oauth 도메인의 soft delete 정책 반영
<br/>
```java
@SQLRestriction("deleted_at IS NULL")
@SQLDelete(sql = "UPDATE user SET deleted_at = NOW() WHERE id = ?")
public class User extends DateAuditable {
...
}
```
- `@SQLDelete` : JPA에서 `delete` 쿼리가 호출되어야 할 때, 여기서 선언한 쿼리가 대신 호출됨.  
- `@SQLRestriction` : `findBy`, `exists`를 사용할 때, 기본으로 `WHERE deleted_at IS NULL` 조건이 붙음
<br/>
</div>
1. 유저가 삭제되면 deletedAt이 업데이트된다.
2. 유저가 삭제되면 findBy와 existsBy로 조회할 수 없다.
3. 유저가 삭제되지 않으면 findById로 조회할 수 있다.
<br/>
- SoftDelete를 위한 어노테이션의 용도가 이해가 되었는지?
- 추가로 수행해봐야 할 테스트가 있는지? (테스트 케이스 작성법 자체에 대해서 질문주셔도 좋아요)
<br/>
> 디코에 먼저 공유한 내용이긴 한데, 워낙 재밌는 내용이기도 하고 admin-api 개발할 때 주의해야 할 거 같아서 공유합니다.
```java
@Test
@DisplayName("[명제] em.createNativeQuery를 사용해도 영속성 컨텍스트에 저장된 엔티티를 조회할 수 있다.")
@Transactional
public …
```
=> ✨ User, Oauth Entity Soft Delete 반영

pennyway-app-external-api/build.gradle, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserOauthSignMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/mapper/UserSyncMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/resources/payload/oidc-response.json, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java, pennyway-domain/src/main/resources/application-domain.yml, pennyway-infra/src/main/resources/application-infra.yml
- #42 OAuth 계정 요청이 200 OK가 뜨지만, DB에 반영되지 않는 이슈
- 통합 Test case를 작성 (관심사 분리가 실패했다고 볼 수 있겠지만, test case를 작성하지 않으면 이번 PR이 성공함을 보장할 수 없었습니다.)
- OAuth Swagger 일부 수정
<br/>
```java
Oauth oauth = Oauth.of(provider, oauthId, user);
oauthService.createOauth(oauth);
```
- `UserOauthSignMapper`에서 *oauthService.createOauth*()를 추가했습니다.
- User Entity에 역방향 관계가 맺어져 있지 않아서, 영속화된 entity에 Oauth 정보가 주입되지 않아 자동 `insert` 대상으로 식별되지 않는다는 걸 놓쳤던 문제입니다.
- User Entity에서 Oauth 정보를 get 할 일은 거의 없다고 판단하여, 역방향 매핑을 하지 않고 그냥 도메인 서비스를 직접 호출했습니다.
<br/>
```java
if (isSignUpUser.getLeft().equals(Boolean.FALSE) && request.username() == null)
throw new OauthException(OauthErrorCode.INVALID_OAUTH_SYNC_REQUEST);
if (isSignUpUser.getLeft().equals(Boolean.TRUE) && request.username() != null)
throw new …
```
=> ✏️ OAuth 계정 연동 실패 해결 및 테스트 케이스 추가

pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java
- Oauth Entity DB 조회 실패
<br/>
- Provider 타입에 `@Converter` 선언
<br/>
- 없음
<br/>
- 없음
=> 🐛 OAuth Provider 필드 Conveter 누락 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/type/ProfileVisibility.java
- 사용자는 본인의 프로필 정보를 조회할 수 있다.
<br/>
- 요청 `/v2/users/me`
```json
{
"user": {
"id": 1,
"username": "user1",
"name": "홍길동",
"isOauthAccount": false,
"passwordUpdatedAt": "yyyy-MM-dd HH:mm:ss",
"profileImageUrl": "https://example.com/profile.jpg",
"phone": "010-1234-5678",
"profileVisibility": "PUBLIC",
"locked": false,
"notifySetting": {
"accountBookNotify": true,
"feedNotify": true,
"chatNotify": true
},
"createdAt": "yyyy-MM-dd HH:mm:ss"
}
}
```
- 현재 계정이 소셜 계정인지, 일반 회원가입이 된 유저인지 판단용으로 `isOauthAccount` 필드 제공
- 이렇게 안 하면 소셜 계정은 `passwordUpdatedAt`을 null로 반환하거나, null일 땐 응답 필드에서 제외해야 하는데 프론트 측에서 예외 핸들링하기 귀찮아짐.
- 소셜 계정인 경우 `isOauthAccount`가 `ture`고 `passwordUpdatedAt`은 응답 필드에서 제외
- 필드명 그대로 반환하는데, 수정할 필요가 있을까요??
<br/>
- 간단한 기능이라 딱히 없음.
<br/>
- `@Schema`의 대상 필드 타입이 `LocalDateTime`인 경우 `example`의 값이 …
=> ✨ 사용자 본인 프로필 조회 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/UserAuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/AuthStateDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignInReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtAuthenticationFilter.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/access/AccessTokenClaimKeys.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/refresh/RefreshTokenClaimKeys.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/WebSecurityUrls.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCaseUnitTest.java
- FE 팀 Page deletegate를 위한 토큰 만료 검증 API
- 필요성
- 사용자가 `API 호출이 필요없는 화면`(ex. 설정창)으로 이동하는 경우
- Client는 API를 호출하지 않으므로 사용자가 설정창으로 이동해도 되는지(로그인 여부)를 알 수 없습니다.
- 따라서 `token`의 유효성 여부만을 확인하여, 사용자 로그인 상태를 응답으로 반환하는 API 제공
- 실제로 Naver나 여러 사이트에서 사용합니다.
</div>
<br/>
1. `Authorization` 헤더가 없거나, `Bearer {Token}` 타입의 문자열이 아닌 경우
```json
{
"data": {
"isSignIn": false
}
}
```
- 로그인하지 않은 사용자라고 판단하고 `false` 응답 반환
2. 유효한 토큰을 제공한 경우
```json
{
"data": {
"isSignIn": true,
"userId": 1 // token에서 추출한 userId
}
}
```
- 로그인한 사용자라고 판단하고 `true` 응답 반환
3. `Authorization` 헤더에 `Bearer {Token}` 형식으로 요청을 보냈으나 유효하지 않은 경우
- JwtErrorCode에 정의한 예외가 발생합니다.
- 명백히 인증 시도를 수행한 것으로 판단했기 때문에 `true`가 아닌 예외를 던져, Client가 핸들링하도록 처리했습니다.
<br/>
```java
JwtClaims claims = …
```
=> ✨ 로그인 상태 확인 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/OauthController.java
- iOS팀에서 변경된 API 반영됨을 확인하여 Depreacted API 제거
<br/>
- AuthController와 OauthController의 *sendCode*() 메서드 제거
- 이전 PR에서 반영했어야 했는데 커밋 놓친 로그인 확인 API 스웨거 문서 수정 첨가..ㅎ
<br/>
- 없음
<br/>
- 없음
=> ✏️ 인증번호 전송 API 통합에 따른 Deprecated API 삭제

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/Device.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
- 사용자 아이디(username) 수정 API 구현
- 사용자 이름(name) 수정 API 구현
<br/>
</div>
- 요청 경로
- 이름 수정 : `PUT /v1/users/me/name`
- 아이디 수정 : `PUT /v1/users/me/name`
테스트 케이스가 많아서 그렇지 로직은 단순하기 그지 없습니댜.
<br/>
- 변경 요청을 위해 `PUT` 메서드를 사용하는 것이 적절한지?
- 요청 `url`이 적절한지?
- 하려면 Query Parameter로 분리할 수 있긴 함.
- 다만 그렇게 하면 거대한 `if-elseif-else`이 탄생할 수도 있을 것 같아서 보류
<br/>
</div>
- 기존에 정상적으로 동작하던 `em.createQuery()`가 `TransactionRequiredException (Executing an update/delete query)` 예외를 발생시키며 실패함.
- 해당 에러는 선언적 Tx(`@Transactional`)가 없으면 발생한다는데, 해당 테스트에는 분명이 어노테이션이 존재함.
- 실패한 해결 방법
1. `@Modifying` 어노테이션 추가 -> 실패
2. `em.joinTransaction();`으로 트랜잭션 참여 -> PessimisticLockingFailureException 데드락 에러 발생
3. EntityManager를 Autowired가 아닌 `@PresistenceContext`로 호출 -> PessimisticLockingFailureException …
=> ✨ 사용자 아이디/이름 수정 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/converter/NotifyTypeConverter.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/WebConfig.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/NotifySetting.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
- 사용자 알림 on/off API 구현
<br/>
- 기존에 상의한 대로 활성화는 `PUT`, 비활성화는 `DELETE` 요청을 보내도록 했습니다!
- QueryParameter로는 `NotifySetting` Embedded 클래스 내에 정의한 열거 타입 `NotifyType`을 사용했습니다.  
- 테스트 케이스를 작성하려다가...이전 PR하고 거하게 충돌나버릴 것 같아서 ㅎㅎ 병합 후에 따로 PR 작성해서 쓰겠습니다.
- 정상 동작은 확인했으나, 테케가 없어서 증명이 어렵네요 ㅜ
<br/>
- 요청 경로 및 url이 적절한지?
<br/>
- 없음
=> ✨ 사용자 알림 설정 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthCheckApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/PhoneVerificationDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/PhoneVerificationService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthCheckUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckControllerTest.java
- 아이디 찾기 API 요청 시 `phone`과 `code`의 값이 넘어오지 않음
<br/>
- 기존에는 Controller의 인자를 각각 `String`에서 받아왔으나, `DTO`로 받아오도록 변경하였음
- 아이디 찾기 API 요청 시 `phone`과 `code`의 값이 넘어오지 않는 테스트 케이스 추가
<br/>
- 수정 후 결과 (`phone`과 `code`의 값을 입력하지 않았을 경우)
<br/>
- `@RequestParam`과 같이, 인자를 `query-string`으로 선언하는 어노테이션을 별도로 명시하지 않았으나 `query-string`으로 처리됨
- 이에 대한 이유 분석 필요
=> 🐛 아이디 찾기 API 요청 시 휴대폰 번호 및 인증 코드를 입력하지 않을 경우 INTERNAL_SERVER_ERROR 해결

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/AuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/OauthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/UserAuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/UserSyncDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserGeneralSignService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserOauthSignService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCaseUnitTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
> ⚠️ LoC가 좀 긴데, 정말 최소한의 작업만을 수행했음을 알리고 시작합니다.
</div>
- `인증된 사용자`가 소셜 계정을 연동하기 위한 API 구현
<br/>
```java
public enum UserErrorCode implements BaseErrorCode {
...
/* 409 Conflict */
ALREADY_SIGNUP(StatusCode.CONFLICT, ReasonCode.RESOURCE_ALREADY_EXISTS, "이미 회원가입한 유저입니다."),
...
}
```
```java
public enum OauthErrorCode implements BaseErrorCode {
...
/* 409 Conflict */
ALREADY_SIGNUP_OAUTH(StatusCode.CONFLICT, ReasonCode.RESOURCE_ALREADY_EXISTS, "이미 해당 제공자로 가입된 사용자입니다."),
...
}
```
- `400 Bad Request`에 해당하던 값을 `409 Conflict`로 수정했습니다.
- Client가 API에서 제공하는 ErrorCode로 예외 핸들링을 수행하는 만큼, 최대한 중복을 제거하기 위해 수정하게 되었습니다.
<br/>
```java
@Transactional
public void linkOauth(Provider provider, SignInReq.Oauth request, Long userId) {
OidcDecodePayload payload = …
```
=> ✨ 인증된 사용자의 소셜 계정 연동 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/OauthOidcHelper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProvider.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/oidc/OauthOidcProviderImpl.java
> 🤗 결론: 테스트 코드 상으로는 문제 없음.
- OAuth Entity의 `@SQLRestriction`을 제거함으로써 기존 소셜 로그인/회원가입 시나리오 검증
<br/>
**🟡 소셜 회원가입 전화번호 검증 시 soft delete된 oauth 정보를 무시한다.**
```java
@Test
@WithAnonymousUser
@Transactional
@DisplayName("같은 provider로 Oauth 로그인 이력이 soft delete 되었으면 성공 응답을 반환한다.")
void signUpWithDeletedOauth() throws Exception {
// given
Provider provider = Provider.KAKAO; // provider는 카카오로 선택
User user = createGeneralSignedUser(); // 일반 회원가입 유저 생성
Oauth oauth = createOauthAccount(user, provider); // 일반 회원가입 유저에 카카오 oauth 정보 추가
userService.createUser(user); // DB에 저장
oauthService.createOauth(oauth);
oauthService.deleteOauth(oauth); // Oauth 정보는 삭제 (soft delete)
phoneCodeService.create(expectedPhone, expectedCode, PhoneCodeKeyType.getOauthSignUpTypeByProvider(provider)); // 전화번호를 redis에 미리 저장
// …
```
=> 🐛 OAuth 로그인/회원가입 시 Soft Delete 정책 반영 검사

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/controller/UserAuthController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserOauthSignService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/OAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCaseUnitTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
- 인증된 사용자가 임의의 Provider 계정 연동을 제거하기 위한 Use Case를 실현하는 API
<br/>
**🟡 요청 스펙**
- method : `Delete`
- url : `/v1/link-oauth`
- parameter : `Provider`
- pre-condition : `isAuthenticated`
<br/>
**🟡 서비스 로직 플로우**
```java
@Transactional(readOnly = true)
public Oauth readOauthForUnlink(Long userId, Provider provider) {
Set<Oauth> oauths = oauthService.readOauthsByUserId(userId); // 사용자가 가지고 있는 모든 Oauth 정보 조회
Oauth oauth = oauths.stream()
.filter(o -> o.getProvider().equals(provider) && !o.isDeleted()) // 삭제되지 않았으면서, Provider가 일치하는 정보 조회
.findFirst()
.orElseThrow(() -> new OauthException(OauthErrorCode.NOT_FOUND_OAUTH)); // 없으면 404 에러
long oauthCount = oauths.stream().filter(o -> !o.isDeleted()).count(); // 삭제되지 않은 Oauth 중 전체 개수 카운트
User user = oauth.getUser(); // Oauth가 가리키는 유저 조회 …
```
=> ✨ 인증된 사용자의 OAuth 연동 해지 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/OauthAccountDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/mapper/UserProfileMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java
</div>
- 소셜 계정 연동 정보를 위한 응답 개선
<br/>
1. `OauthService`를 사용하여 delete 되지 않은 사용자의 연동 provider 정보 조회
2. `UserProfileMapper`를 사용하여 Entity를 Dto와 binding
<br/>
</div>
제건 소셜 계정 연동이 안 되어 있어서 희진님 걸로 확인해봤더니 잘 동작하네요.  
soft delete 처리하면 마찬가지로 false로 나옵니다.  
왜 테스트 케이스를 안 썼냐구요? 그러게요..  
테케 없이도 쉽게 확인 가능한 부분이라 굳이 작성하지 않았습니다.
<br/>
기존에 사용자가 소셜 계정만 있는 유저인지 판단하는 `isOauthUser` 필드값이 있었는데, 이게 다소 모호한 표현이라 생각했습니다.  
예를 들어, 구글 계정을 연동했는데 일반 회원가입을 하면 `isOauthUser == false`라고 반환이 되었거든요.  
그래서 현재는 `isGeneralSignUp` 필드로 수정했습니다.  
이러면 일반 회원 가입 이력이 존재하는지 안 하는지만을 분명하게 표현 가능하다고 판단했습니다. 
<br/>
Mapper를 이렇게 써보면 좋지 않을까..싶어서 사용해봤습니다.  
Mapper를 활용하지 않으면 아래처럼 작성해줘야 합니다.
```java
@Transactional(readOnly = true)
public UserProfileDto getMyAccount(Long userId) {
User user = …
```
=> ✏️ 마이 프로필 조회 시, 소셜 계정 연동 정보 추가

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserDeleteService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/repository/UserRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/service/UserService.java
- 사용자 자신의 계정을 삭제하는 UseCase를 실현하는 API
<br/>
기능 자체는 간단한데, 몇 가지 의문 사항이 있을 것 같아 작성합니다.
이미 알고 계실 수도 있겠지만, Jpa 메서드의 `delete`나 영속화 관계를 사용하여 연관 관계 정보를 삭제하는 아이디어는 양이 많을 수록 성능 저하를 유발합니다.  
- 혹시 모르는 내용이라면 [참고 블로그](https://jojoldu.tistory.com/235)를 확인해보시면 됩니다.
- `deleteAll` 또한 entityManager를 재생성하지 않을 뿐, 내부적으로 반복문을 사용하기 때문에 쿼리가 엄청 많이 나갑니다.
<br/>
따라서 저는 `@Query`를 사용하여 다음과 같이 처리했습니다.
```java
@Transactional
@Modifying(clearAutomatically = true)
@Query("UPDATE Oauth o SET o.deletedAt = NOW() WHERE o.user.id = :userId AND o.deletedAt IS NULL")
void deleteAllByUser_IdAndDeletedAtNullInQuery(Long userId);
```
- 벌크 연산을 이용해 한 번에 삭제하는 방식입니다.
> 🤔 `deleteAllInBatch`를 쓰지 않은 이유? `clearAutomatically = true`는 또 뭔가요?
> 
> `clearAutomatically = true` 옵션이 없으면 해당 메서드는 `deleteAllInBatch`와 큰 차이가 없습니다.
> 그런데 벌크 연산의 가장 큰 문제는 …
=> ✨ 사용자 계정 삭제 API 

pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCaseTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/Device.java
- 사용자 삭제 시, 매핑된 device 정보 삭제 확인
- unique 필드에 해당하는 phone과 username의 처리
<br/>
코드는 딱히 수정된 게 없습니다.  
Device에서 User 매핑을 할 때 `CaseCade.Remove` 속성을 줌으로써 삭제가 되는 것을 확인했습니다.
```java
@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE)
@JoinColumn(name = "user_id")
private User user;
```
<br/>
User의 `phone`과 `username`의 경우, 삭제가 되면 null로 수정하려고 했는데 문제가 있었습니다.  
> 현재는 DB에서 두 필드 모두 unique로 설정되어 있어서, 회원 탈퇴한 유저가 동일한 번호로 회원가입하거나, 다른 사용자가 탈퇴한 사용자의 닉네임을 사용하려 하는 경우 문제가 발생합니다.
</div>
1. null로 수정하려면 `phone`과 `username`의 not null 옵션을 해제해야 합니다.
2. null로 수정하면 unique한 값이 되지 않으므로 이 또한 해제해야 합니다.
즉, 전화번호와 아이디를 null로 처리하는 방식은 두 필드의 not null과 unique를 옵션을 모두 제거해야 합니다.  
하지만 not null을 제거하는 건 데이터를 저장할 때 위험하지 않을까 싶어서 `unique` 옵션만을 해제하고, 사용자가 계정을 삭제해도 전화번호와 아이디를 삭제하지 않는 방향으로 수정하려 합니다.
<br/>
- …
=> 🐛 사용자 삭제 시나리오 개선

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingSearchRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSaveService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingCategoryManager.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingUseCaseIntegrationTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/dto/CategoryInfo.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/exception/SpendingErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomCategoryRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java
> 엄청 금방 끝낼 줄 알았던 기능인데, 고려할 게 생각보다 너무 많아서 죽는 줄..
- 사용자가 지출 내역을 등록하기 위한 Usecase를 실현하는 API
<br/>
- url : `POST /v2/spendings`
- pre-condition
- 사용자는 로그인한 상태여야 한다.
- 사용자가 커스텀 카테고리를 선택한 경우, 해당 카테고리의 소유권이 있어야 한다.
- usecase
1. 사용자 데이터를 조회한다.
2. 사용자에게 지출 내역을 등록한다.
<br/>
*🟡 통합 테스트 항목*
1. request의 categoryId가 -1인 경우, spendingCustomCategory가 null인 Spending을 생성한다.
2. request의 categoryId가 -1이 아닌 경우, spendingCustomCategory를 참조하는 Spending을 생성한다.
3. 사용자가 categoryId에 해당하는 카테고리 정보의 소유자가 아닌 경우, 403 Forbidden을 반환한다.
<br/>
- `Spending` 생성자, 카테고리 업데이트 메서드에 상태 조건문 추가
- `Dto` 매핑 시 상태 조건문 추가
너무 과하게 한 감이 없지 않아 있긴 한데, 혹시라도 발생할 수 있는 상태 불일치 문제를 예방하기 위함입니다.  
라고 하기엔 중복적인 부분도 많은 거 같아서 나름 덜어낸다고 덜어낸 건데..^^  
참고로 상태 불일치라고 하면 `Spending` entity의 `category`가 "Other"이라서 `customCategory`를 참조하려고 보니 null이라던가..그런 문제를 이야기 합니다.
- …
=> ✨ 지출 내역 등록 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingCategoryApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingCategoryUseCase.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/SpendingCategoryConverter.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/Spending.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/domain/SpendingCustomCategory.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomCategoryRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java
- 사용자는 본인이 추가한 지출 카테고리를 조회할 수 있다.
<br/>
> 너무 단순한 작업이기도 하고, 굳이 테스트 케이스를 보일 이유가 없어서 작성하지 않았습니다.
> 대신 스웨거 이미지로 대체
- url : `GET /v2/spending-categories`
- pre-condition : 사용자는 로그인한 상태여야 한다.
- usecase
1. 사용자가 등록한 커스텀 카테고리 리스트 조회
<br/>
</div>
- 서비스에서 제공해주는 카테고리는 iOS팀에서 기본으로 UI에 출력하고, 추가로 등록한 카테고리만 반환함.
<br/>
- 테스트 케이스...필요하신가요? ㅋㅋㅋ 뭘 써야 할 지 모르겠어서...
<br/>
일단 현재는 해결한 바보 이슈긴 한데, 디버그 정보 활용하는 걸 좀 알게 돼서 공유드립니다.  
처음에 계속 DB를 조회하는 과정에서 `Out Of Index` 에러가 발생해서 로그를 확인해봤습니다.
</div>
```sql
SELECT scc.*
FROM spending_custom_category scc
LEFT JOIN user u ON u.id = scc.user_id
WHERE u.deleted_at IS NULL AND scc.deleted_at IS NULL AND u.id=10;
```
- Extracted JDBC value의 키-값은 [`select 절에 정의한 필드 번호`] - [`매칭된 값`]을 의미합니다. (전 귀찮아서 그냥 scc.*로 표현 ㅎ)
- 데이터를 잘 가져오다가 3번 째 인덱스에 …
=> ✨ 사용자 정의 지출 카테고리 조회 API

pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryDslSearchRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryDslSearchRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/repository/QueryHandler.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/user/repository/UserExtendedRepositoryTest.java
- #76 의 Dto 불변성 보장 실패를 개선
<br/>
</div>
- 만약 `bindings`의 구현체가 `LinkedHashMap`인 경우 입력 순서를 보장할 수 있기 때문에 `Projections.bean()`이 아닌 `Projections.construtor()`을 사용할 수 있습니다.
- 생성자를 사용할 수 있다면 더 이상 Reflection을 사용한 주입 방법을 고수할 필요가 없어지므로 `record`를 사용하여 Dto의 불변성 또한 유지할 수 있습니다.
- 단, 구현체가 LinkedHashMap이 아닐 수 있기에 예외적으로 핸들링하고 있으며, LinkedHashMap을 사용하더라도 "반드시 생성자 순서에 맞게" 자료구조에 값을 담아야 합니다.
<br/>
- 테스트 코드에 HashMap을 사용한 방식과 LinkedHashMap을 사용한 방법 모두 명시해두었습니다. 확인해보시고 이해가 안 가는 부분에 대해서 질문해주세요!
<br/>
- 없음
=> ✏️ QueryDsl 확장 Repository의 Dto 불변성 보장을 위한 분기 처리

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/SwaggerConfig.java
- Swagger 응답 예시가 "string"으로 뜨는 문제 수정
- Api 갯수가 늘어남에 따라 도메인 별로 분리하는 작업 수 
<br/>
</div>
- "전체 보기"를 포함하여 현재는 총 4가지로 분리했습니다.
- 아이러니하게도...전 분리만 했을 뿐인데 응답이 정상적으로 출력되기 시작함;
<br/>
- 딱히 없음.
<br/>
</div>
- 전체 보기에선 응답 예시 에러가 해결되지 않음.
- 개별 보기에선 해결됨.
- 이유를 모르겠으나..전체 보기는 말 그대로 api 파악용으로 만든 거라 딱히 상관 없다고 생각해서 별도로 수정하지 않을 예정.
=> 📝 Spring Docs Swagger UI 수정 및 API 그룹 매핑

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authentication/SecurityUserDetails.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/filter/JwtAuthenticationFilter.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/UserAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/AuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/OAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/UserAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java
- 기존의 커스텀 어노테이션 `@WithSecurityMockUser`의 한계점 발견
- 테스트에서 요청 사용자 정보를 확보하는 데 있어 일관되고, 안정성을 보장하는 방법으로 수정
<br/>
- 통합 테스트 환경에서 `@WithSecurityMockUser(userId = "1")`를 사용하여, 요청한 사용자의 정보를 Controller의 `@AuthenticatePrincipal`에 삽입하는 데 성공했습니다.
- 하지만 `userId`의 default가 1이기 때문에 테스트를 작성하는 개발자가 임의의 테스트에 저장된 Mock User의 id를 예측하여 어노테이션에 전달해줘야 하는 리스크가 존재했습니다.
<br/>
> 매우 간단한 해결책..
```java
User user = userService.createUser(user); // 영속화된 유저 생성
UserDetails userDetails = SecurityUserDetails.from(requestUser); // UserDetails 객체 생성
mockMvc.perform(...)
.with(user(userDetails));
```
- 기존의 `@WithSecurityMockUser` 어노테이션을 모두 제거하고, `mockMvc`를 요청할 때 UserDetails를 `.with(user())`로 전달하면 끝납니다.
- 더 이상 테스트 순서에 구애받지 않아도 되며, 개발자가 사용자 아이디 예측샷을 할 필요도 없습니다.
<br/>
- 해당 어노테이션을 통합 테스트에서 사용하는 건 제약이 있을 수 있지만, 여전히 유용한 것은 사실입니다.
- 요청자의 …
=> ✏️ 테스트 작성 시 `@AuthenticatePrincipal` 어노테이션 대응

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/TargetAmountApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/exception/TargetAmountErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/service/TargetAmountService.java
- 사용자는 당월 목표 금액을 삭제할 수 있다.
<br/>
> 규칙만 알면 너무 간단한 API라, 따로 테케는 작성하지 않았습니다.
- 사용자가 장기 미접속자인 경우, 기간 내의 데이터가 존재하지 않음.
- 사용자가 접속은 했으나 당월 목표 금액을 등록하지 않거나, 삭제한 상태 → 레코드를 추가하고 `amount = -1`로 저장
이거 이해하면 끝남.
<br/>
- url : `DELETE /v2/targets/{date}`
- path parma
- `date` : 시스템 상의 시간과 "년도"와 "월"이 일치해야 함.
- error
- 당월 요청이 아닌 경우 : 400
- 당월에 등록한 데이터가 없는 경우 : 404
- 등록은 했으나 이미 삭제(amount==-1)된 경우 : 404
<br/>
- 사용자한테 pk를 넘겨주고 있지 않다보니, 경로로 date를 받고 있긴 한데 괜찮은 방법일지?
- query로 받으면 `/v2/targets?date=`가 돼서 전체 조회 같이 보일 것 같음.
<br/>
- 없음.
=> ✨ 당월 목표 금액 삭제 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/SpendingManager.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/exception/SpendingErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
- 사용자는 본인이 작성한 지출내역을 상세 조회 할 수있다.
<br/>
> 간단한 동작이어서 테스트케이스를 아직 작성하지 않았습니다. 다만, 조회를 시도하는 사용자의 ID가 지출 내역의 작성자 ID와 일치하지 않을 때에 대한 통합 test 를 작성해야할지 고민중에 있습니다.
test 케이스를 작성하지 않은 대신에, 로컬환경에서 정상적인 조회 및 예외처리가 발생함을 확인하였습니다.
- url : `GET /v2/{지출내역 ID}`
- pre-condition : 사용자는 로그인 한 상태이고, 조회하고자 하는 지출 내역의 작성자 여야 한다.
결과 응답
```json
{
"data": {
"id": 1,
"amount": 10000,
"category": {
"isCustom": false,
"id": -1,
"name": "식비",
"icon": "FOOD"
},
"spendAt": "2021-08-01 00:00:00",
"accountName": "카페인 수혈",
"memo": "아메리카노 1잔"
}
}
```
응답은 기존에 작성되어있는 `SpendingSearchRes.Individual`을 사용하였습니다.
<br/>
- **"`SecurityUserDetails` 유저와 지출 상세내역 작성자가 같은지?"** 를 검사하는 로직이 `UseCase`단에 위치하는게 옳은가? 에 대해서 고민했던 것 같은데. 이 부분에 대해서 어떻게 생각하시는지 궁금합니다.
<br/>
X
=> ✨ 지출 내역 상세 조회 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingSearchRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingMapper.java
- 지출 내역 조회 시, Swagger에서 param을 query가 아닌 header로 받는 오류
- `monthlySpendingAmount` 필드 제거
<br/>
- header로 값을 받던 부분을 query로 수정
<br/>
- key를 `spendings`에서 `spending`으로 수정
- 지출 목록 조회 시, 월별 총 소비 금액 계산 로직 제거.
- 이 부분은 목표 금액 조회할 때 어차피 조회가 가능하며, 목표 금액과 월별 총 소비 금액은 언제나 함께 요청이 되기 때문에 그쪽 api로 묶음.
<br/>
- 해당 요청에서 월별 총합을 계산하는 로직을 제거하기로 한 것에 대해서 사전에 이야기를 하긴 했으나, 혹시나 지금이라도 포함되는 게 맞다고 생각하신다면 말씀해주세요!
<br/>
- 없음
=> 🐛 지출 내역 조회 응답 및 스웨거 버그 픽스

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/interceptor/SignEventLogInterceptor.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/JwtClaimsParserUtil.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/WebConfig.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthCheckControllerTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/SpendingControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/question/controller/QuestionControllerTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/IpAddressHeaderConverter.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLog.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLogRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/sign/SignEventLogService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/domain/SignInLog.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/domain/SignInLogId.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/repository/SignInLogRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/service/SignInLogService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/sign/type/IpAddressHeader.java
- 사용자가 로그인을 하면 로그인 이력을 caching한다.
- 사용자의 기기 정보는 `User-Agent` 헤더를 통해 전달한다.
<br/>
- SignEventLog
- Redis에 저장하기 위한 Hash Table
- `userId`를 key로 가지며, ttl은 현재 24시간으로 설정
- SignInLog
- MySQL에 저장하기 위한 Entity
- B+ tree 순차 탐색 성능을 높이기 위해 `signedAt + id` 복합키를 갖는다.
<br/>
</div>
- AOP로 처리할 지, Interceptor로 처리할 지 고민했으나 web과 밀접한 기능이므로 Interceptor로 처리하는 것이 옳다고 판단했습니다.
- 일반 로그인, 소셜 로그인, 리프레시 API 에만 동작하며, 아직까진 User-Agent 헤더가 없어도 예외를 반환하지 않습니다.
- 혹시나 클라이언트에서 동의를 구해야지만 정보를 추출할 수 있는 경우를 대비하여, 확인 후 조치할 예정
- 하게되면 `preHande()`을 구현하여 처리할 수 있음.
<br/>
- `JwtAuthHelper`에 Util의 성격에 가까운 메서드가 포함되어 있어 전부터 고치고 싶었는데, 이번에 함께 수정하게 됐습니다.
- 수정을 하지 않으면 불필요하게 빈을 주입 받아야만 메서드를 사용할 수 있어 같이 수정하게 되었습니다.
<br/>
- 모든 흐름은 오늘 대면으로 전달해드렸기 때문에 PR에 자세히 남기진 않았습니다. 그럼에도 혹시나 이해가 안 가는 부분이 있다면 다시 질문해주세요!
- 예상 외로 수정된 코드 라인 수가 …
=> ✨ 사용자 로그인 로그를 위한 Interceptor 및 환경 구축 

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
사용자는 지출 내역을 삭제할 수 있다.
<br/>
- url : `DELETE /v2/{지출내역 ID}`
- pre-condition : 사용자는 로그인 한 상태이고, 삭제하고자 하는 지출 내역의 작성자여야 한다.
결과
통합테스트 결과
<br/>
> 로직 자체는 다 합쳐서 10줄이내입니다.
<br/>
> **Scenario**
- 사용자는 없는 지출 내역 삭제를 시도
- `@PreAuthorize`의 `hasPermission`메서드가 해당 사용자 id + 지출 내역 id를 포함한 지출내역 레코드가 `isExist` 하는지 확인
- `false` 일시 403`FORBIDDEN` 예외 발생
위 시나리오에서, 없는 지출내역의 삭제 요청이 들어왔을때도 똑같이 `isExist` 구문이 `false`가 나오므로 권한 예외가 발생합니다. 즉, 틀린 예외가 발생합니다.
- 개선 방안
`hasPermission` 메서드의 권한 인증 로직을 변경한다.
> **FROM** `spendingId` + `userId`로 존재하는 레코드가 있는지? 
> **TO** `spendingId로 존재하는 레코드가 있는지?` + 있다면, `spendingId` + `userId`로 존재하는 레코드가 있는지?` 로 변경하기
잠재 위험 -> 레코드의 존재여부를 검사하는 로직이 권한검사에서 한번, `UseCase`단에서 한번 존재하며, 관심사가 잘못됨.
사실상 클라이언트단에서 다른 사용자의 지출내역 삭제 요청이 들어올 일은 없긴하지만, 비정상적인 요청에도 고려해야한다는 점에서 고민이 됩니다. 좋은 의견있으면 공유해주시면 감사하겠습니다!
=> ✨ 지출 내역 삭제 API

.github/workflows/create-tag-and-release.yml
내용은 사실 버그 픽스지만 ㅎㅎ  
태그 자동 생성 시 main 브랜치가 아닌 브랜치는 pre-release 처리되어서 브랜치 명이 태그의 접미사로 붙는 기능이 있었는데  
개인 저장소에서 위와 같이 설정했을 때 정상적으로 태그가 발행되는 것을 확인하긴 했습니다.  
제발 잘 되길 빌어주세요.  
로컬 테스트 로그 화면.
=> Api: 🎇 Api-v1.0.0 릴리즈

.github/workflows/create-tag-and-release.yml, .github/workflows/deploy-batch.yml, .github/workflows/deploy-external-api.yml
- workflows에서 발생한 이벤트가 다른 workflows의 trigger로 동작하지 않음을 발견
- 태그 생성 파이프라인에서 다음 workflows를 호출하도록 수정
<br/>
1. 임의의 workflows에서 발생한 이벤트를 다른 workflows가 감지하도록 하는 기행은 불가능함. 반드시 외부에서 발생한 이벤트여야 함. 
2. 그렇다면 tag & release 자동화 이후 실행될 workflows를 명시해주어야 함.
- 방법1. workflow_run : 태그 생성 CD가 종료되는 이벤트를 감지하여 배포 CD 실행. → 모든 배포 관련 workflows가 실행되어야 해서 기각
- 방법2. workflow_call : 태그 생성 CD가 다음으로 진행할 배포 CD 선택 → step이 아닌 job 단위에서 실행해야 한다는 단점
- 방법3. workflow_dispatch : 다른 repository의 workflow를 호출하기 위한 것이므로 기각
- 방법4. Composite Actions : step 단위에서 사용할 수는 있으나 다루기가 귀찮은 점이 한 두가지가 아님.
3. 테스트
첫 번째 run에서 module과 version 정보를 출력값으로 설정
4개의 run을 만들어서 module명에 맞는 run이 다음 workflows를 호출
위에서 전달한 값을 inputs.tag로 받아서 배포 파이프라인 실행
<br/>
테스트를 위해 제거했던 PR merged 조건문 추가
전 단계가 수행되지 않으면, 이후 workflows는 별도로 체크 안 해줘도 실행 안 됨을 확인.
<br/>
- 아직 플로우가 이해가 …
=> Api: 🐛 태그 생성 & 릴리즈 자동화 파이프라인 후 배포 workflows call

pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/MailEventHandling.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MailConfig.java
- 문의하기 메일 API 응답속도 문제를 인식 후, 개선하기 위함
<br/>
문의하기 메일 발송 로직을 비동기 처리토록 하기 위해 `@EnableAsync` 어노테이션을 Configuration에 달아주고, `@Async` 어노테이션을 이벤트 핸들러에 달아줌으로써 비동기 처리가 가능케 했습니다.
<br/>
`@EnableAsync`를 사용시 고려되는 부작용이있는지?
<br/>
문의하기 발송 로직은`@TransactionalEventListener`를 사용해 메일을 보내는 작업은 이벤트 핸들러가 작업을 수행합니다. 단순히 이를 사용하기만 해도 비동기 처리가 된다고 생각 했었는데, 아니었습니다. 😅 
위 사진에 나와있듯이, 이벤트를 발행하는 곳과 이벤트를 감지해 특정한 동작을 수행하는 곳이 같은 스레드였습니다.
=> Api: ✏️ 문의하기 응답속도 개선을 위한 이벤트 핸들러 비동기 처리

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/TargetAmountApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/TargetAmountDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/TargetAmountMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/RecentTargetAmountSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountCustomRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/repository/TargetAmountCustomRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/target/service/TargetAmountService.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/target/repository/RecentTargetAmountSearchTest.java
</div>
- 사용자의 가장 최근 목표 금액을 조회하는 API 필요
<br/>
</div>
- 시스템에 기록된 사용자의 가장 최근 목표 금액을 조회한다.
- `amount`는 -1이 아니어야 한다.
- 당월 목표 금액 정보가 반환될 수도 있다.
- 당월 목표 금액이 있는 상태에서 해당 API를 호출하는 건 있어서는 안 되는 경우라고 별도로 처리하지 않음.
- 응답 데이터에서 isPresent 필드를 사용해 amount 필드 여부를 확인할 수 있도록 함.
<br/>
- isPresent 필드를 제거하고, 없으면 amount = -1을 넘길까 고민 중
<br/>
- 없음
=> Api: ✨ 최근 목표 금액 조회 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/question/dto/QuestionReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileUpdateDto.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/question/controller/QuestionControllerTest.java
문의하기 API에 글자수 상한 제한이 없어 추가 및 사용자 이름 정규표현식 수정
<br/>
`QuestionReq` dto 수정
글자수 상한 에러 발생 테스트 작성
`SignUpReq`, `UserProfileUpdateDto` 수정
<br/>
`@Size` 어노테이션의 사용이 적절한지?
<br/>
X
=> Api: ✏️ 문의하기 API content 글자 수 제한 및 사용자 이름 정규식 수정

pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java
기존 월별 지출내역 조회에 user_id 를 검증하는 `WHERE` 절의 누락으로 인해 로그인된 사용자의 지출내역 뿐만이 아닌 다른 사용자의 데이터까지 조회 해오는 문제 발생.
<br/>
`WHERE`절과 필요 없는 `LEFT JOIN`절 제거
<br/>
**쿼리문이 이번엔 적절한지?** 😢
로그인된 사용자의 지출내역 == 조회한 지출내역을 검증하는 테스트의 작성이 필요할까요?
혹시나 찝찝하다면 작성 후 병합 하겠습니다 :)
<br/>
X
=> Api: 🐛 월별 지출내역 조회 쿼리 버그 수정

pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/service/SpendingSearchServiceTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingCustomCategoryFixture.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java
CI 환경에서 `SpendingSearchServiceTest.java`의 간헐적 테스트 실패가 확인되어 이슈 체크 및 수정의 필요성 대두.
<br/>
원인은 일단 **외래키 제약조건**의 위반이었습니다.
`Spending` 객체가 `SpendingCustomCategory` 테이블에 존재하지 않는 id를 spending_custom_category필드의 값으로 가지게 되면서 위반되었던 것이었습니다.
> 코드를 다 때려 넣어서 설명하다가 너무 복잡해서 간단하게 줄였습니다.
- `SpendingSearchServiceTest.java`에서 테스트를 위해 커스텀 카테고리를 가지는 `Spending` 객체들을 bulkInsert하는 과정이 존재하는데, 이를 수행하기 위해서는 먼저 커스텀 카테고리들을 DB에 생성해 주어야 함.
- 이 때문에 `SpendingCustomCategoryFixture` 에서 커스텀 카테고리를 capacity 개 만큼 DB에 bulkInsert 함.
- 그 후, capacity 만큼의 `Spending`들을 DB에 저장함. 이때 CustomCategory 필드에 들어갈 id(외래키) 값은 {1~capacity}사이에서 **랜덤으로** 뽑았음. `1 + FLOOR(RAND() * %d)`
1\~capacity 사이의 값들에서 랜덤으로 뽑는 과정이 무엇인가 잘못 된 것 같은데, 제가 직접 찍어본 결과 잘못될 수가 없습니다...
분명히 capacity 개의 커스텀 카테고리들이 저장되고, `Spending` 객체들을 생성할때는 1\~capacity 사이의 id를 사용하는데 여기서 없는 id를 …
=> Api: 🐛 N+1 문제 개선 테스트의 간헐적 실패문제 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/api/SpendingCategoryApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/controller/SpendingCategoryController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/SpendingCategoryDeleteService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/SpendingCategoryUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/SpendingCategoryIntegrationTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
- 사용자는 사용자 지정 카테고리를 삭제할 수 있다.
<br/>
- url : `DELETE /v2/spending-categories/{categoryId}`
- pre-condition : 사용자는 로그인 한 상태이고, 삭제하고자 하는 사용자 정의 카테고리의 작성자여야 한다.
결과 응답
```json
{
"code" : "2000",
"data" : { }
}
```
<br/>
`@OnDelete`등과 같은 방법을 통해 DDL을 통한 연쇄 삭제를 사용할 것인지 아니면 비즈니스 로직에서 직접 연쇄 삭제를 구현해야 할지 고민하다가 일단은 조금더 명시적인 방법인 후자를 택했습니다.
어떤 방법이 더 좋을지 의견주시면 의논 후 반영토록 하겠습니다.
<br/>
단위 테스트를 작성해보려 했으나... **삭제 행위**에 있어서 단위테스트가 의미가 없다고 판단했습니다.
삭제 동작 같은 경우에는 **실제로 DB에서 데이터가 제거가 되었는지?** 가 중심적인 관심사인데, 단위 테스트를 진행하면 Mock 객체의 동작(여기서는 DAO계층의 동작) 결과를 개발자가 전부 직접 제공해주어야 하기 때문입니다.
혹시나 이런 상황에서 의미있는 단위테스트를 작성할 수 있는 방법이 있으면 알려주시면 감사하겠습니다 :)
=> Api: ✨ 사용자 정의 카테고리 삭제 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountDeleteService.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountIntegrationTest.java
- iOS 팀에서 추천할 최근 목표 금액이 없을 시, DELETE 요청을 수행하면 404 NOT FOUND 예외 발생
<br/>
```java
TargetAmount targetAmount = targetAmountService.readTargetAmount(targetAmountId)
.filter(TargetAmount::isAllocatedAmount)
.orElseThrow(() -> new TargetAmountErrorException(TargetAmountErrorCode.NOT_FOUND_TARGET_AMOUNT));
```
기존에는 "amount == -1", 즉 목표 금액이 설정되어 있지 않는 데이터를 필터링해도 무방했습니다.  
하지만 목표 금액에 `is_read`라는 필드가 추가되면서, 목표 금액이 할당되어 있지 않을 때에서 is_read를 false로 바꾸기 위해 DELETE 요청을 보내는 Usecase가 추가되었습니다.  
따라서 filter를 제거하여 요청을 성공적으로 처리하도록 수정했습니다.
<br/>
- 없음
<br/>
- 없음
=> Api: 🐛 목표 금액 DELETE 유즈 케이스 잘못된 필터링 제거

.github/workflows/open-api-code-review.yml, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingSearchRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/TargetAmountDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/SpendingMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/mapper/TargetAmountMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/service/TargetAmountSaveService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/usecase/TargetAmountUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/controller/TargetAmountControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/ledger/integration/TargetAmountIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/SpendingFixture.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/dto/TotalSpendingAmount.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
- #128 
- 각각의 소비 내역은 int 범위 내에서 지정 가능하지만, 지출 총합 시 int 범위를 초과할 수 있으므로 long 타입으로 수정.
<br/>
long 타입 수정하면서, 기존에 무분별하게 원시 타입과 래퍼 타입을 혼용하던 것을 다소 보완했습니다.  
long 타입을 벗어나는 경우는 고려하지 않았습니다.  
현실적으로 long 타입을 벗어날 정도가 되려면
```
2,147,483,647 x χ = 9,223,372,036,854,775,807
χ > 4,294,967,296
```
`χ`개 만큼의 소비 내역이 존재해야 하는데, 이 정도면 악의적인 공격이라고 밖에 볼 수 없으며, 시스템에 큰 지장을 준다고 생각도 안 되기에 별도의 예외 처리를 하지 않았습니다.
<br/>
- Wrapper Type과 Primitive Type을 혼용해서 사용하고 있는데, 타입 캐스팅으로 인한 오버헤드가 심각하게 발생할 만한 부분이 존재하는지?
<br/>
당월 목표 금액 데이터가 없으면, 총 소비내역도 확인이 불가능한 이슈가 존재함.  
하지만, 해당 API는 어디까지나 "당월" 목표 금액과 총 지출 금액을 조회하려는 용도로 개발되었으며, 정상적인 플로우에서 당월 목표 금액 데이터가 존재하지 않는 경우는 없음.   
따라서 해당 이슈가 ciritcal하지 않다고 판단하여, 별도로 예외처리 하지 않음.
=> Api: ✏️ 총 지출 총합 값의 정수 범위 초과 케이스를 고려하여 타입 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/SmsApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/query/VerificationType.java
```java
public enum VerificationType {
GENERAL("general"),
OAUTH("oauth"),
USERNAME("username"),
PASSWORD("password"),
PHONE("phone");
private final String type;
VerificationType(String type) {
this.type = type;
}
public PhoneCodeKeyType toPhoneVerificationType(Provider provider) {
return switch (this) {
case OAUTH -> PhoneCodeKeyType.getOauthSignUpTypeByProvider(provider);
case USERNAME -> PhoneCodeKeyType.FIND_USERNAME;
case PASSWORD -> PhoneCodeKeyType.FIND_PASSWORD;
default -> PhoneCodeKeyType.SIGN_UP;
};
}
}
```
- 사용자의 QueryParam을 VerificationType으로 받고 PhoneCodeKeyType으로 치환하는 과정에서 `phone` 변환 분기 처리를 빠트림.
- case 하나 더 추가하고, default인 경우 예외를 던져 해결할 수도 있지만 보다 근본적인 휴먼 에러 발생 원인을 찾아서 제거
<br/>
개인적으로 switch문을 좋아하지 않습니다.  
상수가 추가될 때마다 개발자가 case 문을 추가하는 방식은 번거로움과 휴먼 에러 가능성의 여지를 제공합니다.  
따라서, 각 …
=> Api: 🐛 Sms type 변환 시, 휴먼 에러 제거 및 예방

pennyway-batch/src/main/java/kr/co/pennyway/batch/common/dto/DeviceTokenOwner.java, pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/QuerydslNoOffsetPagingItemReader.java, pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/QuerydslNoOffsetPagingItemReaderBuilder.java, pennyway-batch/src/main/java/kr/co/pennyway/batch/common/reader/options/QuerydslNoOffsetStringOptions.java, pennyway-batch/src/main/java/kr/co/pennyway/batch/reader/ActiveDeviceTokenReader.java
- #124  #137 에서 작업한 쿼리 오류 수정
- QuerydslNoOffsetItemReader 기능 및 Builder 추가
<br/>
> 자세한 이유는 [블로그](https://jaeseo0519.tistory.com/400) 가장 하단에 추가해두었습니다.
```sql
SELECT u.id, u.name, d.token 
FROM device_token d
INNER JOIN user u ON d.user_id = u.id AND u.deleted_at IS NULL
WHERE d.activated = true AND u.account_book_notify=true AND u.id > currentId AND u.id <= lastId
ORDER BY u.id
LIMIT 0, chunkSize;
```
```
-> Limit: 1000 row(s)  (cost=2532.33 rows=274) (actual time=0.077..44.888 rows=1000 loops=1)
-> Nested loop inner join  (cost=2532.33 rows=274) (actual time=0.076..44.758 rows=1000 loops=1)
-> Filter: ((u.account_book_notify = true) and (u.id > 0) and (u.id <= 5000) and (u.deleted_at is null))  (cost=1932.82 rows=479) (actual time=0.050..2.891 rows=2590 loops=1)
-> Index range scan on u …
```
=> Batch: 🐛 정기 푸시 알림 배치 쿼리 픽스 & ItemReader 기능 수정

pennyway-batch/src/main/java/kr/co/pennyway/batch/common/dto/AnnounceNotificationDto.java, pennyway-batch/src/main/java/kr/co/pennyway/batch/job/MonthlyTargetAmountNotifyConfig.java, pennyway-batch/src/main/java/kr/co/pennyway/batch/scheduler/SpendingNotifyScheduler.java, pennyway-batch/src/main/java/kr/co/pennyway/batch/writer/DailySpendingNotifyWriter.java, pennyway-batch/src/main/java/kr/co/pennyway/batch/writer/MonthlyTotalAmountNotifyWriter.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/domain/Notification.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/type/Announcement.java
- 매월 1일이 되면, 지출 관리 푸시 알림을 허용한 사용자의 활성화된 device_token 전체에 푸시 알림을 보낼 수 있어야 한다.
- 사용자가 여러 device_token을 가지고 있더라도, 사용자에게 저장되는 푸시 알림은 하나여야 한다.
<br/>
</div>
- 다른 건 이전 배치 작업이랑 똑같은데, 한 가지...문제가...이 공지 알림은 제목에 날짜가 들어간당...ㅎㅎ
- 생성할 땐, 시스템 상의 현재 날짜의 달을 삽입
- 조회할 땐, 데이터의 created_at 정보의 달을 삽입
- 파싱할 때, announcement enum class를 호출하는 측에서 분기 처리해야 함 
- AnnounceNotificationDto의 정적 팩토리 메서드 내에서 title 만들 때, 번거롭게 또 분기처리....
저장 & 조회 모두 잘 되는 것을 확인 함.
<br/>
- `MONTHLY_TARGET_AMOUNT` 상수의 제목 파싱하는 방법이 너무 더럽고, 휴먼 에러를 야기할 수 있다고 생각.
- 하지만 반면으로 "공지" 알림이라는 게 빈번한 수정이 발생할 사안은 아닌 듯 해서 냅둬도 괜찮을 지도.
- 분기처리를 Announcement 호출자 측으로 위임해버리는 바람에, title, content 수정 시 버그가 많아질 것 같아서 대비책을 구상해둘 필요가 있을 것 같음..
<br/>
- 없음.
=> Batch: ✨ 매월 목표 금액 설정 공지 푸시 알림 배치

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserDeleteService.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserDeleteServiceTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/TestJpaConfig.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/repository/DeviceTokenRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/service/DeviceTokenService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingCustomCategoryRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/repository/SpendingRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingCustomCategoryService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/spending/service/SpendingService.java
- User 삭제 시나리오에서 관여하는 Entity가 늘어남에 따라 관련 데이터 삭제 처리
<br/>
- Spending, SpendingCustomCategory 모두 soft delete 처리합니다.
- 디바이스 토큰은 is_activate를 false로 변경합니다. (미리미리 해둬야 나중에 배치가 덜 부담스러워 함.)
- hard delete해야 하는 notification은 삭제 처리하지 않습니다.
- 어차피 해당 데이터는 사용자 본인을 제외하고 조회할 경우가 없음 (관리자도 굳이..)
- 안 그래도 삭제할 작업 많은데, 데이터가 삽시간에 많아지는 notification bulk 삭제한다는 발상보다는 나중에 soft delete 처리한 사용자 보관 만료기간 끝날 때 DB에서 처리하는 게 효율적이라 판단함.
<br/>
- 없음
<br/>
- Fixture 컨벤션을 안 정해놨더니, 진짜 뭔 소린지 몬 알아먹겠음.. 어떻게 할 지 논의가 필요함.
=> Api: ✏️ 사용자 삭제 로직 추가

pennyway-batch/src/main/java/kr/co/pennyway/PennywayBatchApplication.java
- 정기 알림이 새벽 5시에 전송되는 문제 발생
<br/>
- Batch 애플리케이션 실행 환경 타임존 수정
<br/>
- 없음
<br/>
문제가 발생했을 때는 시간이 올바르게 표시되었으나, 현재는 그렇지 않음.  
그런데 실제로 올바른 시간에 푸시 알림이 보내지는 건 위 이미지처럼 시간이 표시될 때;;  
EC2 타임존도 맞춰줬는데 이유를 잘 모르겠음.
=> Batch: 🐛 Batch 애플리케이션 timezone 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/api/StorageApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/controller/StorageController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/dto/PresignedUrlDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/storage/usecase/StorageUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/controller/UserAccountController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/dto/UserProfileDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/mapper/UserProfileMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserProfileUpdateService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/usecase/UserAccountUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/storage/AwsS3Adapter.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/storage/controller/StorageControllerTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/controller/UserAccountControllerUnitTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/client/aws/s3/AwsS3Provider.java
- 프로필 사진 삭제 API 개발
- 기존 presigned url 발급, 프로필 이미지 저장 로직 리팩토링
<br/>
- 프로필 사진 삭제 요청을 하면, DB와 S3 모두 데이터 제거
- 기존 로직에서 외부 API 호출이 Tx 내부에서 실행되는 문제가 있어, `AwsS3Adapter`로 분리
- DB에 cdn 경로를 저장하는 부분은 key만 저장하도록 수정
- 어느 cdn에서 이미지를 받을 지는 요청 패킷 아이피 혹은 쿼리 파라미터로 결정하는 게 맞다고 생각.
- cdn 경로를 삽입하면, 이미지 삭제를 위해 문자열 파싱을 해야 하는데 번거로움.
- 사용자 정보 조회 시, 완성된 프로필 사진 URL을 받을 수 있도록 수정.
<br/>
- DB에 cdn 경로가 아닌 key만을 저장하는 부분이 합리적인지.
<br/>
- 없음.
=> Ignore: ✨ 프로필 사진 삭제 API 및 수정 API 픽스, 리팩토링

pennyway-app-external-api/build.gradle, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/SecurityConfig.java
- 무중단 배포 환경 구축을 위해 actuator 설정
<br/>
- `GET /actuator/health`을 하면 애플리케이션 헬스 체크가 가능함.
<br/>
- 없음
<br/>
- 없음.
=> Ignore: ✨ 애플리케이션 헬스 체크를 위한 Actuator 의존성 추가

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java
- 전역 예외 핸들러 설정 추가
<br/>
잘못된 요청 메서드에 대해 서버사 500 에러를 반환하는 문제가 있었음.
전역 예외 핸들러에서 `HttpRequestMethodNotSupportedException`를 처리하도록 수정
<br/>
- 없음.
<br/>
- 없음.
=> Api: ✏️ HttpRequestMethodNotSupportedException 전역 예외 설정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/DeviceTokenUnregisterService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/DeviceToken.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/domain/User.java
- device token을 삭제하면, 부모를 같이 삭제하는 1+1 이벤트 행사 중단.
<br/>
- 무슨 생각이었는지 모르겠지만...자식 Entity에서 cascade 옵션으로 `REMOVER`를 주면, 자식 Entity를 삭제할 때 부모도 같이 삭제된다.
- 자식이 부모에 대한 cascade 설정은 옵션값이므로 그냥 제거.
<br/>
정상 동작 확인
<br/>
- 없음
<br/>
- 없음.
=> Ignore: 🐛 Devcie Token 삭제 시, 사용자가 정보 삭제되는 에러 핸들링

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/handler/GlobalExceptionHandler.java
- 사용자가 쿠키를 삽입하지 않고 요청을 보냈을 때 500 에러를 반환하는 문제
<br/>
<br/>
- 없음
<br/>
- 없음
=> Ignore: 🐛 Missing Request Cookie Header 예외 핸들러 추가

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/api/UserAccountApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/DeviceTokenRegisterService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/DeviceTokenUnregisterService.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/DeviceTokenRegisterServiceTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/DeviceTokenUnregisterServiceTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/domain/DeviceToken.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/exception/DeviceTokenErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/device/service/DeviceTokenService.java
- 사용자의 세션이 만료된 Device Token 정보 관리를 위해 자동으로 Update되는 `updated_at` 필드가 아닌, `last_signed_in` 필드가 필요함.
- 로그아웃 시, token을 제거하는 로직이 추가됨에 따라 device_token 테이블에 너무 빈번한 CD 작업이 발생할 우려가 있음.
<br/>
- Device Token의 `DateAuditable` 상속 제거
- 직접 created_at 자동 설정, 수동 last_sigend_up 업데이트를 위한 필드 및 메서드 추가
<br/>
- 원래는 회원 탈퇴만을 고려했었는데, 로그아웃 요청일 때도 device_token을 비활성화 할 필요가 있음
- 따라서 삭제 요청을 하면, device token을 삭제하지 않고 `deactivate` 시킴
<br/>
- token에 대한 정보가 없으면 새로 생성하는 로직은 동일
- 만약 존재하면, 바로 반환하지 않고 `last_signed_in` 필드를 갱신하여 반환
<br/>
- 왜 `last_signed_in`이 필요한가?
- 사용자가 로그아웃을 하면, token을 비활성화 하여 푸시 알림이 보내지는 것을 방지하고 있습니다.
- 하지만, 사용자가 로그아웃하지 않고 7일 이상 앱을 실행하지 않는다면, 저희 앱에선 "사실상 로그아웃 상태"로 취급합니다.
- 따라서 푸시 알림을 전송하기 전에 Device Token의 유효성을 검사할 때, `last_signed_in` 토큰 또한 검사할 필요가 존재합니다.
<br/>
- 없음.
=> Api: ✏️ Device Token Session 관리를 위한 로직 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/api/UserAuthApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/UserSyncDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserGeneralSignService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/UserOauthSignService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/UserAuthUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/OAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/UserAuthControllerIntegrationTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/domain/Oauth.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/exception/OauthErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/repository/OauthRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/oauth/service/OauthService.java
- 연동하려는 소셜 계정이 이미 다른 사용자 계정에 연동되어 있을 때 예외 처리
- soft delete된 데이터를 복구하지 않는 정책으로 수정
<br/>
- 필드: id, oauth_id, provider, created_at, deleted_at, user_id
- {id}는 유일성을 보장함.
- {oauth_id, provider}는 유일성을 보장하지 않음. candidate 성립 X
- 임의의 provider 계정을 사용자1의 계정에 연동했다가 해지 후, 사용자2의 계정에 연동할 수 있기 때문
- deleted_at이 NULL인 {oauth_id, provider}는 유일성을 보장해야 함. (임의의 provider의 계정이 연동된 서비스 계정은 최대 하나여야 한다.)
- {user_id, provider}는 유일성을 보장하지 않음.
- 사용자가 임의의 provider 계정1에 연동했다가 해지 후, provider 계정2에 연동할 수 있기 때문
- Optional<Oauth> readOauthByUserIdAndProvider(Long userId, Provider provider) 에러 발생 가능성 존재.
- deleted_at이 NULL인 {user_id, provider}는 유일성을 보장해야 함. (사용자가 임의의 provider에 연동된 계정은 최대 하나여야 한다.)
<br/>
- 완전히 새로운 소셜 계정 정보를 연동하는 경우를 제외하고는 삭제된 데이터를 복구하는 방식으로 데이터를 추가함.
- 이로 인해, candidate에 해당하지 않는 조건으로 OAuth 정보를 조회하면, 정보가 2개 이상일 …
=> Api: ✏️ OAuth 계정 연동 누락된 예외처리 수정 (OAuth 연동 정책 수정)

.github/workflows/deploy-external-api.yml
- 서비스 안정성 향상을 위한 무중단 필요성 대두
<br/>
```mermaid
graph TD
A[시작] --> B{현재 실행 중인 서비스 확인}
B -->|Blue| C[Green 서비스 선택]
B -->|Green| D[Blue 서비스 선택]
C --> E[새 버전 이미지로 선택된 서비스 시작]
D --> E
E --> F{헬스 체크}
F -->|성공| G[이전 서비스 중지 및 제거]
F -->|실패| H[새 서비스 중지 및 제거]
G --> I[nginx 설정 업데이트]
H --> J[이전 서비스 재시작]
I --> K[배포 완료]
J --> L[롤백 완료]
```
- docker-compose.yml 수정 (was)
```yml
...
was_blue:
container_name: was_blue
image: pennyway/pennyway-was:${WAS_VERSION}
ports:
- "${WAS_BLUE_PORT:-8080}:8080"
environment:
- TZ=Asia/Seoul
env_file:
- .env
depends_on:
- rdb
- cache
was_green:
container_name: was_green
image: pennyway/pennyway-was:${WAS_VERSION}
ports:
- "${WAS_GREEN_PORT:-8081}:8080"
environment:
- TZ=Asia/Seoul
env_file:
- .env
depends_on:
- rdb
- cache
```
- nginx.conf 수정 (bastion)
```yml
upstream …
```
=> 🔧 Blue-Green 배포를 위한 deploy script 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/api/NotificationApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/controller/NotificationController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/dto/NotificationDto.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/mapper/NotificationMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/service/NotificationSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/usecase/NotificationUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/notification/controller/GetNotificationsControllerUnitTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/repository/NotificationRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/service/NotificationService.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/notification/repository/ReadNotificationsSliceUnitTest.java
- 기존에 확인 알림과 미확인 알림을 합쳐버리니, 무한 스크롤이 뒤섞이는 문제가 발생함.
- iOS 측 요청에 따라 확인 알림과 미확인 알림을 분리
<br/>
- 기존 API 변경 사항
- 미확인 알림 존재 여부를 판단하기 위한 URL이 `GET /notifications/unread` → `GET /notifications/unread/exist`로 수정
- 구현된 API
- url: `GET /notification/unread`
- 해당 경로로 요청한 데이터는 무한 스크롤이 아닌, 전체 데이터를 모두 반환함. (단, 모든 데이터는 시간 순(id)으로 역정렬되어, 최신순서가 가장 앞의 인덱스에 위치.)
<br/>
- 미확인 알림 여부 조회를 위한 경로를 `/notifications/unread/exist`로 일단 지정해뒀는데, `exist` 대신 대체할 만한 게 있을 지..?
<br/>
- 현재 푸시 알림 타입 구분없이 모든 알림에 대해 무한 스크롤을 사용하는데, 채팅 메시지도 여기서 확인 가능하게 되면 문제가 생길 여지가 있음. 이에 대해 디자이너와 상의가 필요함.
=> Api: ✏️  확인 알림과 미확인 알림 조회 API 분리

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/socket/api/SocketApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/socket/controller/SocketController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/socket/service/ChatServerSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/socket/usecase/SocketUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/InfraConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/SwaggerConfig.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/client/coordinator/CoordinatorService.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/client/coordinator/DefaultCoordinatorService.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/client/coordinator/WebSocket.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/importer/PennywayInfraConfigGroup.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/config/DistributedCoordinationConfig.java, pennyway-infra/src/main/resources/application-infra.yml
</div>
채팅 서버와 Socket 연결을 위해, Client는 1차적으로 클라이언트의 `물리적 위치(geographical location)`와 `서버의 용량(capacity)`을 기반으로 최적의 채팅 서버 url을 알아야 합니다.  
이번 작업은 이러한 기능을 고려하여 설계되었습니다.  
<br/>
</div>
초기 설계안이라 현재 클래스명과 다소 차이가 있습니다.  
우선 위 설계는 한 가지 가정을 두고 시작합니다.  
- 채팅 서버는 언제든지 유연하게 scale-out 될 수 있다.
- API 서버는 이 채팅 서버 중, 클라이언트에게 가장 최적의 채팅 서버 url을 반환해주어야 한다.
이를 완벽하게 구현하기 위해서는 Apache Zookeeper와 같은 분산 코디네이션 서비스(Distributed Coordination Service)를 사용하겠지만, 당연히 저희는 사용하지 않습니다! 😆
단, 수요가 있을 때, 언제든지 빠르게 적용하기 위해 모듈화의 이점을 극대화하여 위와 같이 설계하게 되었습니다.  
**📝 API Spec**
- 요청: `GET /v2/socket/chat`
- 해당 요청은 API 서버 인증 권한 검사를 수행합니다.
- 응답
```json
{
"data": {
"chatServerUrl": ""
}
}
```
<br/>
- URL 명이 조금 구리네요. 아름다운 이름이 없을까..
<br/>
ChatServerSearchService를 확인하면, CoordinatorService …
=> Api: ✨ 분산 코디네이션 도입을 고려한 서비스 탐색 서비스 API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/InfraConfig.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/config/security/CorsConfig.java, pennyway-infra/build.gradle, pennyway-infra/src/main/java/kr/co/pennyway/infra/client/broker/MessageBrokerAdapter.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/importer/PennywayInfraConfigGroup.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/ChatExchangeProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/RabbitMQProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/RabbitMqProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MessageBrokerConfig.java, pennyway-infra/src/main/resources/application-infra.yml, pennyway-socket/.gitignore, pennyway-socket/build.gradle, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/properties/ChatServerProperties.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/properties/MessageBrokerProperties.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/config/InfraConfig.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/config/WebSocketMessageBrokerConfig.java, pennyway-socket/src/main/resources/application.yml
- WebSocket Server Stomp 및 External Broker 연결 설정
- Message Queue 중앙 관리를 위한 RabbitMQ 연결 설정
<br/>
- RabbitMQ와 Socket Server 간에 AMQP(port: 5672) 연결 설정 완료
- Client 측에서 웹 소켓 연결 시, STOMP(port: 61613) 연결 설정 완료 
<br/>
- 테스트를 위한 html과 js를 구현해두었습니다. 코드는 secret 채널에 압축 파일로 올려둘테니, `pennyway-socket` 모듈 하위의 `resource`에 넣어주고 `docker-compose up -d` 실행 후, html 열어보면 됩니다. (이슈 하나 있는데, 아래 적음)
- 추가된 속성이..매우 많습니다.
<br/>
- 이유를 모르겠으나, IntelliJ로 실행하면 Socket Server가 RabbitMQ와 연결은 하는데 ConnectFactory 생성과 Exchange 등록을 정상적으로 수행하질 않음. (??)
- 이미 혼자 공부하면서 똑같이 설정했을 때 모두 동작했고, 로컬에서 실행하면 여전히 잘 되기 때문에 이유를 못 찾는 중.
```
PENNYWAY_PROXY_IP=*
CHAT_SERVER_URL=ws://localhost:8081/chat
SOCKET_SERVER_PORT=8081
```
- 만약, 테스트를 해보고 싶다면, 위와 같이 환경 변수 수정 → `socket` 컨테이너 내리고 인텔리제이로 실행하시면 됩니다.
=> Ignore: ✨ RabbitMQ 및 Socket 서버 연결 설정

pennyway-socket/src/main/java/kr/co/pennyway/socket/common/dto/ServerSideMessage.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/exception/InterceptorErrorCode.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/exception/InterceptorErrorException.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/StompCommandHandlerFactory.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/StompExceptionInterceptor.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/StompInboundInterceptor.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/handler/AbstractStompExceptionHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/marker/ConnectCommandHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/marker/StompCommandHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/marker/StompExceptionHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/marker/SubscribeCommandHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/security/authenticate/UserPrincipal.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/security/jwt/AccessTokenClaim.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/security/jwt/AccessTokenClaimKeys.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/security/jwt/AccessTokenProvider.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/util/StompMessageUtil.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/config/WebSocketMessageBrokerConfig.java, pennyway-socket/src/main/resources/application.yml
- Interceptor 접근 시 필요한 작업을 반영하기 위한 환경 구축 (ex. 인증/인가 필터링)
- Interceptor 예외 발생 시, 전역 핸들링을 위한 환경 구축
<br/>
디자인 패턴을 있는 대로 때려박았습니다.  
Security 라이브러리처럼 친절하게 인터셉터를 등록할 수 있는 구조가 아니어서, 자체적으로 구현하게 됐습니다.  
**🟡 Inbound Interceptor**
1. 애플리케이션 시작 시, `StompCommandHandlerFactory`에서 마커 인터페이스 `StompCommandHandler`를 구현한 모든 핸들러를 가져와 STOMP 명령어 별로 핸들러를 구분합니다.
2. 클라이언트 요청이 들어오면, `ChannelInterceptor`를 구현한 `StompInboundInterceptor`에서 명령어 종류에 따라 `StompCommandHandlerFactory`에 등록한 핸들러를 실행시킵니다.
옵저버 패턴을 사용하지 않은 이유는 Interceptor의 실행 결과를 다시 돌려받아야 하기 때문..
**🟡 Exception Interceptor **  
위랑 거의 동일한데, 여기선 STOMP 프레임이 아닌 예외를 기준으로 핸들링하기 때문에 Factory는 나오지 않습니다.  
1. 예외 처리 필터를 등록하기 위해서는 `StompExceptionHandler` 인터페이스를 구현합니다.
- 그러나 예외는 거의 비슷한 플로우로 처리되기 때문에, 이를 템플릿 메서드 패턴으로 구현해둔 `AbstractStompExceptionHandler`를 상속받아서 처리해도 됩니다.
2. …
=> Ignore: ✨ WebSocket Inbound & Exception Interceptor

pennyway-socket-relay/src/main/java/kr/co/pennyway/PennywaySocketRelayApplication.java, pennyway-socket/src/main/java/kr/co/pennyway/PennywaySocketApplication.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/handler/AuthenticateExceptionHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/handler/ConnectAuthenticateHandler.java
[스프링 공식 문서](https://docs.spring.io/spring-framework/reference/web/websocket/stomp/authentication-token-based.html)의 명세에는 다음과 같이 적혀있습니다.
- 서버 측 세션을 유지하지 않는 애플리케이션이나 인증을 위해 헤더를 사용하는 것이 일반적인 모바일 애플리케이션에선 쿠기 기반 세션이 항상 적합하지는 않다.
- [RFC 6444](https://datatracker.ietf.org/doc/html/rfc6455#section-10.5)에선 "WebSocket hand-shake 중에 서버가 클라이언트를 인증할 수 있는 특정 방법을 규정하지 않는다"고 명시되어 있다.
- 그러나 실제로는 브라우저 클라이언트는 표준 인증 헤더 또는 쿠키만 사용 가능하며, 사용자 지정 헤더를 제공할 수 없다.
- SockJS에서도 Authorization 헤더를 지정할 수 없음에 대해, 2019년까지 [활발한 논의](https://github.com/sockjs/sockjs-client/issues/196)가 이어졌다. 
- 사람들은 대안책으로 Query Parameter로 Access Token을 전달하는 대안을 내놓았지만, 토큰이 서버 로그의 URL과 기록될 수 있다는 고유한 단점이 존재한다.
- HTTP 프로토콜 수준에선 충분한 대안이 없을 테니, STOMP 메시징 프로토콜 수준에서 헤더로 인증하는 방법을 고려해봐라.
- STOMP Client를 사용해, Connect 시점에 인증 헤더를 전달하고, ChannelInterceptor를 …
=> Ignore: ✨ Authenticate the Inbound and Exception Interceptor when using the Connect Frame

pennyway-socket/src/main/java/kr/co/pennyway/socket/common/event/ReceiptEventHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/event/RefreshEvent.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/controller/AuthController.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/AuthService.java
- 사용자의 Principal `expiresAt` 만료 시, refresh 요청을 처리하는 컨트롤러
- #166 의 후작업
<br/>
- Connect 프레임에서 사용자 인증을 수행하지만, API 서버에서 사용자 권한이 만료되었음에도 WebSocket 연결은 가능하다는 문제가 존재함.
- 이에 `Principal`의 `expiresAt`을 access token 만료 시간으로 설정하여, `isAuthenticate` 메서드에서 만료 여부를 판단
- Client가 API 서버에서 refresh를 수행하여 성공하면, 이번에 작업한 path로 principal의 expiresAt 필드를 갱신할 수 있음.
- 성공 혹은 실패 여부를 클라이언트 측으로 receipt
<br/>
- 없음.
<br/>
- 다 작성하고 생긴 의문. Principal은 client - server 간에 맺어진 헤더를 기반으로 추출함. 그렇다면 클라이언트에서 이 값을 조작할 수 있지 않은가?
- 일반적인 시나리오에선 Connect 단계에서 검증했기 때문에, 문제가 되지 않음.
- 만약 토큰을 탈취한 공격자가 한 번이라도 웹 소켓 연결에 성공하면, 이 값을 조작하여 무한 연결을 유지할 우려가 존재함.
- 따라서, 클라이언트 측에서 헤더를 조작할 수 있는 지 검증 후 대안책을 마련할 필요가 존재함.
=> Ignore: ✨ Controller for updating the principal's expiresAt field 

pennyway-infra/src/main/java/kr/co/pennyway/infra/client/guid/IdGenerator.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/client/guid/TsidGenerator.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/importer/PennywayInfraConfigGroup.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/config/GuidConfig.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/config/InfraConfig.java
- 실시간 채팅 정보를 DB에 저장하는 것에는 무리가 있기에, NoSQL에 일정 기간 캐싱을 해둘 예정.
- 이로 인해, `auto_increment` 방식의 고유 ID를 생성할 수 없음.
- 따라서, 애플리케이션 단에서 다음의 요구 사항을 충족하는 GUID 생성기를 구축할 필요성 제기
- ID는 유일성을 보장해야 한다.
- ID는 숫자로만 구성되어 있어야 한다.
- ID는 64bit로 표현 가능해야 한다. 
- ID는 발급 날짜에 따라 정렬 가능해야 한다.
- 초당 10,000개의 ID를 만들 수 있어야 한다. (절충할 수 있는 부분)
<br/>
- 라이브러리는 [f4b6a3](https://github.com/f4b6a3/tsid-creator)을 사용했습니다.
- 64-bit(timestamp(42bit) + node(8bit) + counter(14bit)) 크기를 가지며, 128-bit UUID에 비해 훨씬 적은 공간을 차지합니다.
- node bit 8-bit는 Factory로 조절할 수 있지만, 저희가 채팅 서버를 8개나 띄울 일이 없습니다.
- 분산 코디네이션 없이, 각 서버에게 node id를 할당하기도 어렵기 때문에 8-bit로 고정해버렸습니다.
- counter bit가 14-bit이므로, ms 당 16,383개의 고유 ID를 생성할 수 있습니다.
- 정수 데이터를 가지기 때문에 DB 조인 성능이 상당히 빠릅니다.
- ID 순서로 정렬하면, 곧 생성 순서와 동일합니다.
- `created_at`은 동일 ms에서 생성한 데이터를 정렬하지 못 하기 때문에, id가 이를 수행할 수 있어야 …
=> Socket: ✨ GUID Configuration based on a Time-Sorted Identifier

pennyway-infra/build.gradle, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/ChatExchangeProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MessageBrokerConfig.java, pennyway-socket/build.gradle
로컬 환경에서 실행할 때는 RabbitMQ의 connection factory가 정상적으로 생성되었고,  
심지어 테스트를 위해 개인적으로 구축해놓은 환경에서도 멀쩡하게 동작했으나,  
도커 컨테이너로 올리기만 하면 일을 안 하는 스프링 덕분에 참으로 힘겹고 고단한 시간을 보냈습니다.  
심지어 아무런 로그도 안 뜨고, 그냥 연결이 안 되는 최악의 상황  
close #171 
<br/>
```java
@Bean
ApplicationRunner connectionFactoryRunner(ConnectionFactory cf) {
return args -> cf.createConnection().close();
}
```
결론부터 이야기하면, 위 방법으로 해결했습니다.  
Application이 시작하면, 강제로 ConnectionFactory 연결을 실행하도록 하여 작업을 수행합니다.  
<br/>
눈물없인 볼 수 없는 고생한 과정들.
1. 빈 초기화가 되는 것을 확인하기 위해 로그를 출력했는데, 모두 정상 초기화가 되고 있었음. (빈 초기화 문제 아님)
2. 로컬에서 dev 프로필로 실행해도 성공, 도커 컨테이너에서 local 프로필로 실행하면 실패. (프로필 문제는 아님)
3. 환경 변수 오기입을 했으면, 인증 실패 예외가 발생했을 것이므로 패스. (socket에서 STOMP 연결은 무사히 성공하는 것만 봐도 이건 아님)
4. docker-compose 설정 문제 → 기존에 성공했던 테스트 프로젝트와 완전히 동일한 세팅임에도 실패
5. 로그를 살펴보니 serverlet 단에서 연결을 수행 중. web …
=> Socket: 🐛 Resolving the issue where Spring Boot does not create a RabbitMQ connection factory

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/ledger/dto/SpendingReq.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/ExternalApiDBTestConfig.java, pennyway-domain/build.gradle, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/UserStatusConverter.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/session/SessionLuaScripts.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/session/UserSession.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/session/UserSessionRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/session/UserSessionRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/session/UserSessionService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/session/UserStatus.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/config/RedisConfig.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redis/session/UserSessionCustomRepositoryTest.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/config/ContainerDBTestConfig.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/config/ContainerRedisTestConfig.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/contants/StompNativeHeaderFields.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/dto/StatusMessage.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/event/ReceiptEvent.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/event/ReceiptEventHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/exception/InterceptorErrorCode.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/exception/MessageErrorCode.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/exception/MessageErrorException.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/handler/inbound/ConnectAuthenticateHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/handler/inbound/DisconnectHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/marker/DisconnectCommandHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/security/authenticate/UserPrincipal.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/config/WebSocketMessageBrokerConfig.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/controller/StatusController.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/AuthService.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/StatusService.java
- 클라이언트의 세션 상태를 다음과 같이 구분합니다.
- 자세한 내용은 [블로그](https://jaeseo0519.tistory.com/418)에 작성
| **상황** | **상태** | **처리** |
| --- | --- | --- |
| 사용자가 앱을 실행 중이지만, 채팅 관련 뷰(내가 가입한 채팅방 리스트 뷰 or 임의의 채팅방 뷰)를 보고 있지 않음. | ACTIVE\_APP | • 푸시 알림 |
| 사용자가 앱을 실행 중이며, 내가 가입한 채팅 리스트 뷰를 보고 있음. | ACTIVE\_CHAT\_ROOM\_LIST | • 메시지 전달 |
| 사용자가 앱을 실행 중이며, 임의의 채팅방 뷰를 보고 있음. | ACTIVE\_CHAT\_ROOM\_{chat\_room\_id} | • 메시지 전달   • 다른 채팅방 메시지는 푸시 알림 |
| 사용자가 앱을 백그라운드로 실행함.   (앱을 종료하지 않고 나가거나, 화면을 끄거나, 메뉴 화면으로 이동) | BACKGROUND | • 푸시 알림 |
| 사용자가 앱을 종료함. | INACTIVE | • 푸시 알림 |
| 사용자가 절전 모드(방해 금지 모드)를 사용함. |   | 중요 알림에 대해서는 기기 설정을 무시하고 보내거나, 배터리 잔량에 따라 동작을 조정할 필요가 있다면...?   너무 복잡한 기능이라 일단 제외 |
| 일정 시간 내 ping을 수신하지 못 함. | INACTIVE | • 푸시 알림 |
| 사용자가 로그아웃을 함. | INACTIVE | • X |
| 사용자가 회원탈퇴를 함. | 사용자 상태 제거 | • X |
| 사용자가 앱을 …
=> Socket: ✨ Managing user session status on a socket server

pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/handler/inbound/ConnectAuthenticateHandler.java
- 잘못된 인자를 전달하여, redis 쿼리 실행 오류
<br/>
- `ConnectAuthenticateHandler` 내부 `activateUserSession`에서 `deviceName`을 전달하던 것을 `deviceId`로 수정
<br/>
- 없음
<br/>
- 없음
=> Socket: 🐛 hash key 인자 전달 휴먼 에러 수정

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatRoomApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/response/SliceResponseTemplate.java
- JSend 프로토콜에 맞추어 Slice 응답 템플릿 수정
- Swagger 수정
- Sql Injection Defense  
<br/>
```json
{
"code": "",
"data": {
"domain": { // 복수 명사에서 단수 명사로 수정
"contents": [ // 단수 명사에서 복수 명사로 수정
],
// ... 이하 동일
}
}
}
```
- 새벽에 웹 프론트 팀과 이야기하다 보니, 단수/복수 명칭을 혼용하고 있는 것 같아 SliceResponseTemplate를 수정했습니다.
- 단, 해당 Template는 최근에 개발한 #181 에만 반영하고, 이전의 무한 스크롤 API들에는 반영되어 있지 않습니다. (수정하면 iOS팀에서 모두 바꿔줘야 함.)
<br/>
JPA는 기본적으로 SQL Injection 공격을 방어해주긴 하지만,  
JPA와 JPASQLQuery를 혼용하고 있기 때문에 혹시나 싶은 상황에 대비하여 몇 가지 키워드를 target parameter로 전달해보았습니다.  
- `;delete from chat_room where id=4;`
- `;drop table chat_room;`
- `;delete from user;`
머쓱할 정도로 잘 막아주더라구요. 허허.  
SQLQueryFactory를 사용하지 않아서, Hibernate 기반의 SQL을 실행할 수 있기 때문에 괜찮다고 판단하였습니다.
<br/>
- 없음.
<br/>
- 없음.
=> Api: ✏️ Modify the format of chat search api

pennyway-infra/src/main/java/kr/co/pennyway/infra/common/properties/RabbitMqProperties.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MessageBrokerConfig.java, pennyway-infra/src/main/resources/application-infra.yml, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/handler/inbound/HeartBeatNegotiationInterceptor.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/properties/MessageBrokerProperties.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/config/WebSocketMessageBrokerConfig.java, pennyway-socket/src/main/resources/application.yml
- Implement negotiation interceptor by [STOMP](https://stomp.github.io/stomp-specification-1.2.html#Heart-beating)
- Currently, there is an issue where the server follows the heartbeat value set by the client.
<br/>
- When using external message broker, the negotiation process is handled by the broker, not by Spring
- But, the RabbitMQ STOMP Plugin doesn't support configuring server-side heartbeat
- So, I implemented an interceptor logic where the heartbeat negotiation is handled by Spring and then passed to RabbitMQ, which consistently follows the client's heartbeat setting.
<br/>
- I've written all the details on my blog. Please refer to the [link](https://jaeseo0519.tistory.com/419) for more informations
<br/>
- none
=> Socket: ✏️ Heartbeat negotiation interceptor

pennyway-app-external-api/src/main/resources/application.yml, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/MessageCategoryTypeConverter.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/converter/MessageContentTypeConverter.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/domain/ChatMessage.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/domain/ChatMessageBuilder.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/domain/MessageCategoryType.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/domain/MessageContentType.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/service/ChatMessageService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/type/MessageCategoryType.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/type/MessageContentType.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepositoryTest.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/config/MessageBrokerConfig.java, pennyway-socket/build.gradle, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/constants/StompNativeHeaderFields.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/constants/SystemMessageConstants.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/constants/SystemMessageTemplate.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/interceptor/handler/inbound/ConnectAuthenticateHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/dto/SendMessageCommand.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/relay/ChatJoinEventListener.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/ChatMessageSendService.java, pennyway-socket/src/main/resources/application.yml
- When the HTTP API publishes a chat-join event, the Socket-relay server listens to it and sends the message into the chatroom
<br/>
- The key for each chatroom message follows the format: `chatroom:{chatroom_id}:message:{chat_id}`
- key's maximum value = (9 characters(`chatroom:`) + 19 characters(`chatroom_id`) + 9 characters(`:message:`) + 19 characters(`chat_id`)) * 2 bytes/char = 112 bytes.
- Given Redis's 512MB key limit (536,870,912 bytes), we don’t need to use a hash algorithm for key compression.
- While we could abbreviate chatroom to cr to save memory, this only confuses monitoring and is inefficient for memory conservation. Therefore, we will use complete words.
<br/>
- same as #184 
- We need to implement this feature within the socket-relay module. However, as mentioned, the …
=> Socket: ✨ Chatroom Join Event Relay

pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/domain/ChatMessage.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepositoryTest.java, pennyway-socket/build.gradle, pennyway-socket/src/main/java/kr/co/pennyway/socket/command/SendMessageCommand.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/controller/ChatMessageController.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/dto/ChatMessageDto.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/relay/ChatJoinEventListener.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/ChatMessageSendService.java
- Authenticated user can send message using Socket API
<br/>
```json
{
"content": "" // Required; max length: 5,000 characters
"contentType": "" // Must match `MessageContentType` capitalization
}
```
- `SEND /pub/chat.message.{chatRoomId}`
<br/>
- Intended format: `chatroom:{chatroom_id}:message:{message_id}`, but was saved with `{classpath}:` prefix.
- Cause: `@RedisHash` lacked a specified value, defaulting to the classpath.
- Update successfully validated.
<br/>
- Switched from entity to DTO for RabbitMQ serialization convenience.
<br/>
- When Socket application is running, output `Shutdown Signal: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'chat.exchange' in vhost '/': received 'direct' …
=> Socket: ✨ Send Chat Message Usecase

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatRoomApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatMemberSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/repository/ChatMemberRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/service/ChatMemberService.java
- When user starts application, It's helping for client to subscribe chatrooms
<br/>
- url: `GET /v2/chatrooms?summary=true`
- pre-condition: authenticated user
- response
```json
{
"data": {
"chatRoom": {
"chatRoomIds": [
1, 2, 3, ...
]
}
}
}
```
<br/>
- Reason for Implementing Joined Chatroom IDs in ChatMemberSearchService:
- Placing this feature in `ChatRoomSearchService` would introduce dependencies impacting unit tests negatively.
- Alternatively, using a class like `ChatRoomsSummarySearchService` would add unnecessary complexity.
- SRP Justification:
- Fetching chatroom summaries relates directly to searching `chat_member` data, thus aligning with `ChatMember` responsibilities.
- This approach simplifies dependencies and enhances testability.
- Considerations:
- Low …
=> Ignore: ✨ Fetch Summary of Chatrooms Joined by User

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatRoomApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatMemberRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatRoomMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomWithParticipantsSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/ChatRoomManager.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/integration/ChatRoomDetailIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatRoomWithParticipantsSearchServiceTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/util/ApiTestHelper.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/domain/ChatMessage.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/service/ChatMessageService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/exception/ChatMemberErrorCode.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/repository/ChatMemberRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/service/ChatMemberService.java, pennyway-domain/src/main/resources/application-domain.yml, pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepositoryImplTest.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepositoryTest.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/ChatMessageSendService.java
- Enable users to retrieve chatroom details (e.g., recent messages, participants, user info) upon accessing the chatroom.
<br/>
Data requirements:
1. myInfo
2. recentChatMessages
3. recentParticipants
4. otherParticipantIds
Since the participant list can reach a max of 300 users, sending all at once is impractical. To handle this, the server will first send recently active participants. The client can then request additional participant details as needed.
<br/>
- request
- url: `GET /v2/chat-rooms/{chatroom_id}`
- pre-condition: Authenticated User, Joined Chatroom
- response
<br/>
Previously, we stored chat messages with a key format of `chatroom:{chatroom_id}:message:{message_id}` in a hash. Although `message_id` is unique and sortable, it didn’t ensure order when saving. By switching to …
=> Ignore: ✨ Receive Chatroom Detail Informations

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatMemberApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatRoomApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatMemberRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatMemberMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatRoomMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatMemberJoinService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/controller/ChatMemberBathGetControllerTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomSaveControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/integration/ChatMemberBatchGetIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatMemberJoinServiceTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatRoomSearchServiceTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/TestJpaConfig.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/chatstatus/domain/ChatMessageStatus.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/chatstatus/repository/ChatMessageStatusCacheCustomRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/chatstatus/repository/ChatMessageStatusCacheCustomRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/chatstatus/repository/ChatMessageStatusCacheRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/chatstatus/repository/ChatMessageStatusRedisRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/chatstatus/repository/ChatMessageStatusRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/chatstatus/service/ChatMessageStatusService.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/config/TestJpaConfig.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/chatstatus/service/ChatMessageStatusServiceIntegrationTest.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/chatstatus/service/ChatMessageStatusServiceTest.java
- User can receive unreadMessageCount. 
<br/>
Remaining tasks will be completed in other branches.
<br/>
1. When the client confirms messages in a chatroom, it sends the last read message ID to the socket server
- `SEND pub/message.read`
```json
{
"chatRoomId": , // for authorization
"messageId":     // for caching user's last read message id
}
```
2. Cache data is saved for 1 hour in Redis.
3. A batch synchronizes cache data with RDB every 10 minutes.
4. When the client requests unreadMessageId from the API server::
- If data exists in Redis, it will be returned.
- Otherwise, it checks RDB and caches the result.
- If no data is found, it returns 0.
5. Updating the additional unread message count in real-time is handled by the client, based on messages received via the socket.
<br/> …
=> Api: ✏️ Append UnreadMessageCount Field in the ChatRoomResponse

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatMemberRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatMemberMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatRoomMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatMemberSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomWithParticipantsSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/controller/ChatMemberBathGetControllerTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/integration/ChatRoomDetailIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatRoomWithParticipantsSearchServiceTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/dto/ChatMemberResult.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/repository/ChatMemberRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/repository/CustomChatMemberRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/repository/CustomChatMemberRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/service/ChatMemberService.java
- iOS 측 요구 사항에 따른 API 스펙 수정
<br/>
1. 채팅방 정보 조회 시, `otherParticipants` 필드에 `name` 필드 추가
2. 최근 활동 이력에 admin이 없거나, 조회하는 클라이언트가 admin이 아니라면 조회 쿼리 추가.
3. 채팅방 멤버 상세 정보에서 `userId` 필드 추가.
<br/>
- 머리가 안 돌아가서, 일단 동작하는 코드로 구현했는데 덕분에 코드가 심각하게 더럽습니다.
<br/>
- 채팅방 메시지 이력이 조회가 안 되는데, 소켓 서버 이미지가 최신화 반영이 안 된 듯. 일단 로컬로 이미지 올리겠습니다.
=> API: ✏️ 채팅방 정보 조회 응답 수정

pennyway-socket/src/main/java/kr/co/pennyway/socket/config/WebSocketMessageBrokerConfig.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/controller/ChatMessageController.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/LastMessageIdSaveService.java
- Continuing from task #190.
- The client will send its last read message ID, which the socket server will retrieve and cache in Redis.
<br/>
- Added message path: `chat.message.{chatRoomId}.read.{lastReadMessageId}`
<br/>
- none
<br/>
- none
=> Socket: ✨ Path to Retrieve Last Message ID

.github/workflows/deploy-batch.yml, .github/workflows/deploy-socket-relay.yml, .github/workflows/deploy-socket.yml
- Add specific service targets to the docker-compose up -d command in the CD pipeline.
- This ensures that when building the batch or socket application, both WAS services (blue/green) aren't deployed together.
<br/>
- Add service targets to the command, excluding the external API service.
<br/>
- none
<br/>
- none
=> Ignore: 🔧 Fix CD Pipeline

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/integration/ChatPaginationGetIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/integration/ChatRoomDetailIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/util/ApiTestHelper.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/common/util/RequestParameters.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/message/service/ChatMessageService.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redis/message/repository/ChatMessageRepositoryImplTest.java
- Implement a Chat History Retrieval API by Chat Room
- Modify the storage method for chat history in Redis.
<br/>
- request
- url: `GET /v2/chat-rooms/{chatRoomId}/chats?chatRoomId=&lastMessageId=&size=`
- pre-condition: authenticated user, chat room accessible by `userId`
- parameter
- chatRoomId
- lastMessageId: oldest message ID read by the client
- size: content size (Optional)
- response
```json
{
"code": ""
"data": {
"chats": {
"contents": [
{
"chatRoomId": 0,
"chatId": 0,
"content": "string",
"contentType": "TEXT",
"categoryType": "NORMAL",
"createdAt": "2024-11-10 14:05:10",
"senderId": 0
},
],
"currentPageNumber": 0,
"pageSize": 0,
"numberOfElements": 0,
"hasNext": true
}
}
```
<br/>
The issue was first discovered during integration testing.  
With `N` data entries saved and …
=> Api: ✨ Chat History Search API (redis score system changed)

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/service/NotificationSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/notification/usecase/NotificationUseCase.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/notification/service/NotificationService.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/domains/notification/repository/ReadNotificationsSliceUnitTest.java
- We had three types of notices, but the designer wants to display only `Announce` type notifications.
<br/>
```java
@Transactional(readOnly = true)
public Slice<Notification> readNotificationsSlice(Long userId, Pageable pageable, NoticeType noticeType) {
Predicate predicate = notification.receiver.id.eq(userId)
.and(notification.readAt.isNotNull())
.and(notification.type.eq(noticeType));
QueryHandler queryHandler = query -> query
.offset(pageable.getOffset())
.limit(pageable.getPageSize() + 1);
Sort sort = pageable.getSort();
return SliceUtil.toSlice(notificationRepository.findList(predicate, queryHandler, sort), pageable);
}
@Transactional(readOnly = true)
public List<Notification> readUnreadNotifications(Long userId, NoticeType noticeType) {
Predicate predicate = …
```
=> Ignore: ✏️ Append WHERE condition in readNotification Query

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/users/service/UserDeleteService.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/users/usecase/UserDeleteServiceTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/repository/CustomChatMemberRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/repository/CustomChatMemberRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/member/service/ChatMemberService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/domains/user/exception/UserErrorCode.java
- Add a restriction in the sign-out process to prevent users from signing out if they hold ownership of any chatrooms.
<br/>
```java
@Slf4j
@Service
@RequiredArgsConstructor
public class UserDeleteService {
...
private final ChatMemberService chatMemberService;
/**
* 사용자와 관련한 모든 데이터를 삭제(soft delete)하는 메서드
* <p>
* hard delete가 수행되어야 할 데이터는 삭제하지 않으며, 사용자 데이터 유지 기간이 만료될 때 DBA가 수행한다.
*
* @param userId
*/
@Transactional
public void execute(Long userId) {
if (!userService.isExistUser(userId)) throw new UserErrorException(UserErrorCode.NOT_FOUND);
if (chatMemberService.hasUserChatRoomOwnership(userId)) {
throw new UserErrorException(UserErrorCode.HAS_OWNERSHIP_CHAT_ROOM);
}
// .. delete process
}
}
```
<br/>
- none
<br/>
- It should be appended deletion processes related user data
=> Ignore: ✏️ Users are unable to delete their accounts while they hold ownership of any chatrooms

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatRoomMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomSaveControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatRoomSearchServiceTest.java
- When client requests `ChatRoomDetail`, the server must include the `lastMessage` field.
- However, this data doesn't need to be highly reliable compared to `unreadMessageCount`. Since any user in the chatroom can send message simultaneously, even if the server retrieves an earlier message, the client will replace the `lastMessage` component with the latest message from the the socket server.
<br/>
```json
{
"chatRooms": [
{
"id": 0,
"title": "string",
"description": "string",
"backgroundImageUrl": "string",
"isPrivate": true,
"isAdmin": true,
"participantCount": 0,
"createdAt": "2024-11-11T05:29:12.715Z",
"lastMessage": { // Append this field 
"chatRoomId": 0,
"chatId": 0,
"content": "string",
"contentType": "TEXT",
"categoryType": "NORMAL",
"createdAt": "2024-11-11T05:29:12.715Z", …
```
=> Api: ✏️ Append LastMessage Field in ChatRoomDetail Response

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignInReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/dto/SignUpReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/AuthUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/usecase/OauthUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/refresh/RefreshTokenClaim.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/refresh/RefreshTokenClaimKeys.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/jwt/refresh/RefreshTokenProvider.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/controller/AuthControllerValidationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/helper/JwtAuthHelperTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/AuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/OAuthControllerIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/auth/integration/UserAuthControllerIntegrationTest.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshToken.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenCustomRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenCustomRepositoryImpl.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenRepository.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenService.java, pennyway-domain/src/main/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenServiceImpl.java, pennyway-domain/src/test/java/kr/co/pennyway/domain/common/redis/refresh/RefreshTokenServiceIntegrationTest.java
- We had a problem:
- To handle the stolen refresh token scenario, we apply the `RTR` technique (saving the user's `valid refresh token` in Redis).
- However, if a client accesses the application from multiple devices, the server mistakenly considers the token stolen because the user's valid refresh token in Redis gets overwritten.
- Therefore, we need to include `device_id` when creating a refresh token and save it in Redis.
<br/>
- The client must send device_id in the following scenarios:
- general & oauth signup
- general & oauth signin
- synchronize general with oauth (2 cases)
- These APIs will now accept additional data.
<br/>
```java
@RedisHash("refreshToken")
@Getter
public class RefreshToken {
@Id
private String id;
private Long userId;
private String deviceId;
...
}
```
- The …
=> Ignore: ✏️ Modification of Refresh Token Specification

pennyway-infra/src/main/java/kr/co/pennyway/infra/common/event/FcmNotificationEventHandler.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/config/InfraConfig.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/relay/ChatMessageRelayEventListener.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/ChatMessageRelayService.java
- Push notifications are not being sent after chat messages are delivered.
- RabbitMQ connection configuration issues identified.
<br/>
- The Tx event handler setting caused events to not trigger after the bounded context ended.
- Instead of modifying the event listener annotation (which could cause other issues), declarative Tx logic was temporarily added to the service layer.
- Removed exclusive configuration in RabbitMQ as it was causing errors.
<br/>
- It seems setting Push Notifications as a Tx event listener was a mistake. Do you agree that a revision is needed?
<br/>
- 없음
=> Ignore: 🐛 Issue with Detecting Push Notification Events

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatMemberJoinService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomWithParticipantsSearchService.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatRoomWithParticipantsSearchServiceTest.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/domain/ChatMember.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/repository/CustomChatMemberRepositoryImpl.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/service/ChatMemberRdbService.java, pennyway-domain/domain-rdb/src/test/java/kr/co/pennyway/domain/member/service/ChatMemberNameSearchTest.java
- The designer requested aligning chat members' names with users' names for consistency.
<br/>
- Removed the `name` field from the `chat_member` table.
- Implemented a database join with the `user` table to fetch names when retrieving chat member data.
<br/>
- none
<br/>
- none
=> Ignore: ✏️ Fix Entity By ChatMember's Name Domain Rule 

pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/account/collection/DeviceTokenCollection.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/account/collection/DeviceTokenRegisterCollection.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/account/service/DeviceTokenRegisterService.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/account/integration/DeviceTokenRegisterServiceIntegrationTest.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/account/service/DeviceTokenRegisterServiceTest.java
- Addressed factors that make TDD challenging.
- For more details, refer to [this blog post](https://jaeseo0519.tistory.com/435).
<br/>
- Business rules are now handled by first-class objects that represent domain rules.
- Service classes now perform integration testing with infrastructure components.
<br/>
- Is the separation of business rules and infrastructure appropriate?
- Are there potential edge cases in how the first-class objects handle domain rules?
<br/>
- DeviceToken Persistence:
- Despite being generated within a transaction (Tx), DeviceToken was not persisted unless explicitly created using a create method. Although the issue has been resolved, the root cause is still under investigation.
=> Ignore: 🔧 Seperate Business Logic From DeviceTokenRegisterService

pennyway-socket/src/main/java/kr/co/pennyway/socket/common/exception/WebSocketGlobalExceptionHandler.java
When a client's message is rejected for some reason, the client cannot handle the issue effectively.  
For example, if the client receives an "unauthenticated" error after sending a chat message, it must resend the message to the server.  
However, since the client cannot identify which message failed, we need to include a message identifier.  
<br/>
- When a business error occurs, the server sends an error message that includes the message's headers.
- If the client adds the `x-message-id` field to the header, they will be able to identify the specific message.
<br/>
- Is the exception handling implemented correctly?
<br/>
- When a `@Validated` error occurs, it isn't handled by `HttpMessageNotReadableException.class`; instead, it is caught by `Exception.class`
- After converting …
=> Ignore: ✏️ Add Send Message Headers to the Error Message

pennyway-socket/src/main/java/kr/co/pennyway/socket/common/aop/PreAuthorizeAspect.kt
<br/>
- Convert the `execute` method's return type from `Any` to `Any?`
<br/>
- none.
<br/>
- none.
=> Socket: 🐛 It Allows the Aspect Class to Return null 

pennyway-socket/src/main/java/kr/co/pennyway/socket/command/SendMessageCommand.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/controller/ChatMessageController.kt, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/ChatMessageSendService.kt
- We improved error messages in #212, but the client still can't handle success messages.  
- Therefore, we need to send a message to notify the client when their chat message is successfully processed.
<br/>
- The server sends a message that includes `x-message-id` to `success queue` after the chat message is successfully published.
<br/>
- Since I am not very experienced with Kotlin, please review the code style.
<br/>
- When the client tries to subscribe, if the receipt header is missing, the server throws an error. 😅
=> Socket: 🔧 The server sends a success message after a chat message is saved successfully

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatMemberApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatMemberController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/ChatRoomManager.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/integration/ChatRoomDetailIntegrationTest.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/chatroom/domain/ChatRoom.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/chatroom/service/ChatRoomRdbService.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/domain/ChatMember.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/exception/ChatMemberErrorCode.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/repository/ChatMemberRepository.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/repository/CustomChatMemberRepository.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/repository/CustomChatMemberRepositoryImpl.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/service/ChatMemberRdbService.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/collection/ChatRoomLeaveCollection.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/service/ChatMemberService.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/service/ChatRoomLeaveService.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/chat/collection/ChatRoomLeaveCollectionTest.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/chat/integration/ChatRoomLeaveServiceIntegrationTest.java
- Chat members can leave a chat room.
- However, the chat room master cannot leave if at least one other member remains in the room.
<br/>
- Implemented business logic for leaving chat rooms.
- Added service unit tests.
- Added service integration tests.
<br/>
- None.
<br/>
- Temporarily disabled the `ChatRoomDetailIntegrationTest` due to a malfunction:
- When a `ChatMember` tries to add itself to the `ChatRoom` fields after the session is closed, a `failed to lazily initialize` error occurs
- While I could use `ChatMemberJoinService` to address this, it has too many dependencies and does not return the `ChatMember` entity.
- I plan to address these issues in the next task.
=> Ignore: ✨ Leave Chat Room API

pennyway-socket/build.gradle, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/aop/PreAuthorizer.kt, pennyway-socket/src/main/java/kr/co/pennyway/socket/common/util/PreAuthorizeSpELParser.kt, pennyway-socket/src/test/java/kr/co/pennyway/socket/common/aop/AuthorizationTest.kt, pennyway-socket/src/test/java/kr/co/pennyway/socket/common/aop/PreAuthorizeAopBenchmark.kt, pennyway-socket/src/test/resources/logback-test.xml
- We were using a custom `@PreAuthorize` annotation to verify user authentication in the socket module.
- While it worked well, synchronization was necessary to avoid conflicts caused by `StandardEvaluationContext` in a concurrent environment.
- Additionally, I wanted to move away from using `Spring AOP`, as it felt cumbersome and inefficient.
<br/>
```kotlin
@MessageMapping(CHAT_MESSAGE_PATH)
@PreAuthorize("#isAuthenticated(#principal) and @chatRoomAccessChecker.hasPermission(#chatRoomId, #principal)")
fun sendMessage(
@DestinationVariable chatRoomId: Long,
@Validated payload: ChatMessageDto.Request,
principal: UserPrincipal,
@Header("x-message-id") messageId: String?
) { ... }
```
- The `@PreAuthorize` annotation relies on string-based expressions.
- These expressions are evaluated in a …
=> Ignore: 🔧 30x Performance Improvement in PreAuthorize AOP

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatMemberApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatMemberController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/exception/ChatMemberErrorCode.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/dto/ChatMemberBanCommand.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/service/ChatMemberBanService.java
- The admin can ban a chat member 
<br/>
- Implement service logic
<br/>
- none
<br/>
- none
=> Ignore: ✨ Ban Chat Member API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatMemberApi.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/account/collection/DeviceTokenRegisterCollection.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/account/service/DeviceTokenRegisterService.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/account/integration/DeviceTokenRegisterServiceIntegrationTest.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/account/service/DeviceTokenRegisterServiceTest.java
- The service was expected to receive only one device token, but four records were returned in the production environment.
<br/>
- Initially, I suspected that duplicate device tokens were being saved.
- However, the issue was simply due to forgetting to delete the historical data that was saved before the business rule changed.
- To resolve this, I deleted all existing device token data and updated some tests.
<br/>
- none
<br/>
- none
=> Ignore: 🐛 Fix Put Device API throws NonUniqueResultException

pennyway-app-external-api/.gitignore, pennyway-app-external-api/src/main/resources/application.yml, pennyway-app-external-api/src/main/resources/logback-spring.xml, pennyway-socket/.gitignore, pennyway-socket/src/main/resources/application.yml, pennyway-socket/src/main/resources/logback-spring.xml
- We had to search for the server logs in the production environment manually.
- It was extremely difficult to locate the logs unless we scanned them immediately after the client reported an issue.
<br/>
- Logs at the `debug` level are now available, except when running the application in the `local` profile.
- All log data is organized by `file size` and `date`
<br/>
- Let me know if you need more details about the log history or if there's anything that should be fixed.
<br/>
- none
=> Ignore: ✨ Log System Implementation

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomPatchHelper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/security/authorization/ChatRoomManager.java, pennyway-app-external-api/src/main/resources/logback-spring.xml, pennyway-socket/src/main/resources/logback-spring.xml
- We couldn’t check the presentation layer’s logs after switching to `logback`.
- Clients receive a 403 error response when attempting to update a chat room, even though they are sending the correct data.
<br/>
- Added appenders to the web and socket modules.
- Fixed the chat room update service logic.
<br/>
- none
<br/>
1. Long-type variables are returned correctly on the server, but the last 2 bits are lost in the Swagger documentation.
2. Forgot to fix the service logic where the chat member search service should join with the user table.
- add some of appenders to web and socket module
- fix api 
<br/>
- none
<br/>
1. Long type variables are correctly return in the server, however, it lost last 2-bits at the swagger doc
2. I forgot to fix service logic that chat member search service …
=> Ingore: 🐛 Improvement of Log System and Update Chat Room API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatRoomApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatRoomMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomSearchService.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java
- The chat room's password is required when an admin tries to modify it.
<br/>
- Added an API for admin view.
<br/>
- none
<br/>
- We need to include information about whether notifications are on or off for each chat room when clients request their joined rooms.
=> Ignore: ✨ Retrieve Chatroom Information in Admin Mode

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatRoomApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatRoomApiV2.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomControllerV2.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatRoomMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatRoomSearchServiceTest.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/chatroom/dto/ChatRoomDetail.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/chatroom/repository/ChatRoomCustomRepositoryImpl.java
- I forgot to include the `NotifyEnabled` field in the `Get Chat Room API` specification. 😅
<br/>
- Reused the existing query and implemented the controller for version 2.
- Once the client team updates their API path, I'll remove the original API.
<br/>
- none.
<br/>
- none.
=> Ignore: 🐛 The NotifyEnabled field has been added to the Get Chat Room API in Version 2

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatRoomApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/dto/ChatRoomToggleCommand.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/service/ChatRoomNotificationToggleService.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/chat/integration/ChatRoomNotificationToggleServiceIntegrationTest.java
- Chat members can turn on/off their individual chat room's notification toggle setting.
<br/>
- `PATCH` request: turn on notification
- `DELETE` request: turn off notification
<br/>
- none
<br/>
- During testing, I turned off notifications for chat rooms `1` and `5`, where I had roles as chat admin and chat member respectively.
- Both operations were processed successfully, but chat room `5` displayed unchanged notification data in the response.
- The actual status was updated correctly, but the response provided incorrect data when requesting chat room details.
- I suspect the issue is due to a mistake in the query changes from PR #225. (It seems I accidentally included the `notify_enabled` field within the aggregation function 🥲).
=> Ignore: ✨ Turn On/Off Chat Room's Notification Setting API

pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/chatroom/repository/ChatRoomCustomRepositoryImpl.java
- Issue #226 
<br/>
- Only move `notify_enable` select query to other query where isn't aggregate function.
<br/>
- none
<br/>
- none
=> Ignore: 🐛 Query to Select Chat Member's Notify Enabled Field Has Been Fixed

pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/chatroom/domain/ChatRoom.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/chat/integration/ChatRoomLeaveServiceIntegrationTest.java
- The reason why leaving a chat room fails is due to an issue in the `hasOnlyAdmin()` method.
- When `Hibernate.size()` is called, it doesn't account for soft-deleted data, causing incorrect behavior.
<br/>
```java
public class ChatRoom extends DateAuditable {
...
@OneToMany(mappedBy = "chatRoom")
@SQLRestriction("deleted_at IS NULL") // Added filter for soft deletion
private List<ChatMember> chatMembers = new ArrayList<>();
```
- Although I dislike using `@SQLRestriction`, it seems acceptable in this case due to its limited scope.
<br/>
- none
<br/>
- none
=> Ignore: 🐛 Add "Is Null" Filter on the Foreign Entity in the Chat Room Entity

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomReq.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/dto/ChatRoomRes.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/mapper/ChatRoomMapper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomPatchHelper.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatRoomUseCase.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/common/storage/AwsS3Adapter.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/controller/ChatRoomSaveControllerUnitTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/integration/ChatRoomCreateIntegrationTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatRoomPatchHelperTest.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/config/fixture/ChatRoomFixture.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/dto/ChatRoomPatchCommand.java, pennyway-infra/src/main/java/kr/co/pennyway/infra/common/exception/StorageErrorCode.java
- I made a mistake to implement API where updating the chat room information due to the complexity of various scenarios:
| | origin image ✅ | origin image ❌ |
|---|---|---|
| non-image | Delete original image | Do nothing |
| new-image | Delete original image, and copy new image | Copy new image |
| exist-image | Only check object existence | ❌ |
- However, I was only handling background images with values of `null` or those starting with the `/delete` prefix.
<br/>
- Removed the `@Pattern` annotation in `ChatRoomReq.Update`.
- Added the required logic in the `ChatRoomPatchHelper`.
<br/>
- none
<br/>
- I also forgot to include the chat member's profile image in the chat member response.  ....^^
=> Ignore: 🐛 Fix Chat Room Background Image Process Logic

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatMemberApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatMemberController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/service/ChatRoomLeaveService.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/chat/integration/ChatRoomLeaveServiceIntegrationTest.java
👌🙆‍♂️🆗
<br/>
The `chat_member_id` field is unnecessary in the Leave Chat Room API, as it does not align with the principles of Domain-Driven Design (DDD). Instead, the required data can be derived from the authenticated user's session or context.  
So remove it.
<br/>
- none
<br/>
- none
=> Ignore: 🔧 Remove Chat Member Id from Leave Chat Room API Spec

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/api/ChatMemberApi.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/controller/ChatMemberController.java, pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/usecase/ChatMemberUseCase.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/domain/ChatMember.java, pennyway-domain/domain-rdb/src/main/java/kr/co/pennyway/domain/domains/member/exception/ChatMemberErrorCode.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/collection/ChatRoomAdminDelegateOperation.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/dto/ChatRoomAdminDelegateCommand.java, pennyway-domain/domain-service/src/main/java/kr/co/pennyway/domain/context/chat/service/ChatRoomAdminDelegateService.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/chat/collection/ChatRoomAdminDelegateOperationTest.java, pennyway-domain/domain-service/src/test/java/kr/co/pennyway/domain/context/chat/integration/ChatRoomAdminDelegateServiceIntegrationTest.java
- The admin should be able to delegate their role to another chat member within the same chat room.
<br/>
- Implemented service and controller logic.
- Added tests for the business logic.
<br/>
Please carefully review potential conflict scenarios.  
For instance, if the chat member who is about to be promoted to admin requests to leave the chat room, this could result in the   chat room having no admin in the worst-case scenario. 😅  
How to Handle This?  
Do you have any good ideas for addressing this?  
Feel free to share your thoughts!
<br/>
- none.
=> Ignore: ✨ Chat Room Admin Delegation API

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/chat/service/ChatRoomPatchHelper.java, pennyway-app-external-api/src/test/java/kr/co/pennyway/api/apis/chat/service/ChatRoomPatchHelperTest.java, pennyway-socket/src/main/java/kr/co/pennyway/socket/service/ChatMessageSendService.kt
- We found an issue where the client fails to update their chat room information when the chat room's profile image remains unchanged.
- The socket server was sending a join message perpetually. Since this was an urgent issue, I fixed it in this PR.
<br/>
- During S3 image validation, the service now removes the prefix from the profile URL.
- The root cause of the infinite message loop was the handling of the success response after sending a message. When the client sent a message, the process confirming the successful transmission triggered an error as the system attempted to publish the message. This led to an infinite consumption loop in the message queue (MQ). To resolve this, I modified the logic to properly handle cases where the sender name is null, preventing the error from …
=> Ignore: 🐛 Remove Prefix During S3 Image Validation & Fix Infinite Invitation Messages

pennyway-app-external-api/src/main/java/kr/co/pennyway/api/apis/auth/service/PhoneVerificationService.java, pennyway-app-external-api/src/main/resources/application.yml
- I implemented a bypass logic for Apple's review in accordance with guideline 2.1.
<br/>
- The system now always considers the phone verification code correct when using the admin phone and code. (Except for finding ID & password)
<br/>
- none
<br/>
- none
=> Api: ✨ Demo Account for Review
